// <auto-generated />
using System;
using System.Text.Json;
using FeevCheckout.Data;
using FeevCheckout.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeevCheckout.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106181928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_attempt_status", new[] { "pending", "created", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "feev_pix", "feev_boleto", "braspag_cartao" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeevCheckout.Models.CardBrandPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardBrandPatterns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aceb18fe-99a6-4a35-91b8-d0dd83dae4cb"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "34"
                        },
                        new
                        {
                            Id = new Guid("67e560e6-51ad-4de2-b9bd-9f76f4012d72"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("64d678b6-65e6-4018-966d-2e9530a36aeb"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("95edd5a0-1e1b-420c-a1ee-b4a1e4360a61"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "37"
                        },
                        new
                        {
                            Id = new Guid("2eae6dd4-3a84-4a06-b7c2-40f556a43c6f"),
                            Brand = "CABAL",
                            Order = 60,
                            Prefix = "6042"
                        },
                        new
                        {
                            Id = new Guid("8799baa1-c5ac-4311-a287-2c90203d16b7"),
                            Brand = "DINERS",
                            Order = 0,
                            Prefix = "605919"
                        },
                        new
                        {
                            Id = new Guid("087325c9-4153-4ba9-921c-8e7b6a9b7b11"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "300"
                        },
                        new
                        {
                            Id = new Guid("f2f87403-1f00-4255-b413-3589f06814ac"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "301"
                        },
                        new
                        {
                            Id = new Guid("83106136-02d3-4a68-8ee9-d1777419301e"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "302"
                        },
                        new
                        {
                            Id = new Guid("bef7804f-070b-4681-b581-1f49ba2480aa"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "303"
                        },
                        new
                        {
                            Id = new Guid("b3d9ab0b-75a7-484c-97dd-610c312428a7"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "304"
                        },
                        new
                        {
                            Id = new Guid("84f7f5a9-20af-4470-b792-75acd7ee3233"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "305"
                        },
                        new
                        {
                            Id = new Guid("15bf01c9-1a14-4087-89d8-9a9d56abb717"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("4a0b9d14-2669-4a39-8417-8ccedbfdff0b"),
                            Brand = "DISCOVER",
                            Order = 1,
                            Prefix = "306262"
                        },
                        new
                        {
                            Id = new Guid("a4706497-f989-4df9-8c26-4aec0f3da14a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6011"
                        },
                        new
                        {
                            Id = new Guid("1f9eec56-2c92-4ec3-b8b2-be1f0a6692d1"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "65"
                        },
                        new
                        {
                            Id = new Guid("af5291eb-c9d1-43c9-9dcf-e091accd92fd"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "644"
                        },
                        new
                        {
                            Id = new Guid("d9199f23-668c-4019-ab96-6319b17f9425"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "645"
                        },
                        new
                        {
                            Id = new Guid("e2545b32-b1ee-4975-9dcd-8442e1152ba3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "646"
                        },
                        new
                        {
                            Id = new Guid("d42be9f9-c32c-4d4d-b08d-ac41c49b9716"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "647"
                        },
                        new
                        {
                            Id = new Guid("e1f465c7-8077-4820-90cf-854cd5f98fc4"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "648"
                        },
                        new
                        {
                            Id = new Guid("32d81310-395c-44b3-8b28-0983cfb5fc66"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "649"
                        },
                        new
                        {
                            Id = new Guid("fc034721-d459-4dd2-82b2-da51c8743c7c"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622126"
                        },
                        new
                        {
                            Id = new Guid("7225a73b-1a07-4172-aa28-a0f1a43fdd1e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622127"
                        },
                        new
                        {
                            Id = new Guid("85072cd6-f40d-4140-a932-2cc43db6364f"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622128"
                        },
                        new
                        {
                            Id = new Guid("6b97a641-4e01-458f-88a1-c4756cb236ba"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622129"
                        },
                        new
                        {
                            Id = new Guid("a7e7a14a-e5cc-47cb-b247-ba355664c21a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62213"
                        },
                        new
                        {
                            Id = new Guid("c8cb5834-8ff1-4b4d-938b-fa3a730dc9a3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62214"
                        },
                        new
                        {
                            Id = new Guid("342af0d3-a1c0-4d5b-a112-b0455e9b2ab3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62215"
                        },
                        new
                        {
                            Id = new Guid("b2e5fda3-90f5-4d95-bfe6-c266377a3ea1"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62216"
                        },
                        new
                        {
                            Id = new Guid("815cf975-492f-43ca-bec3-0c43dc060b91"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62217"
                        },
                        new
                        {
                            Id = new Guid("c63cb1fc-1113-48ed-9254-6d59994b8cfb"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62218"
                        },
                        new
                        {
                            Id = new Guid("2100eb4c-5756-442e-a9ae-49e8e5bd2bf2"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62219"
                        },
                        new
                        {
                            Id = new Guid("88a01aa4-67cc-4038-a592-ae58e02e2ab3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6222"
                        },
                        new
                        {
                            Id = new Guid("32dbc4a8-7102-46d1-9e16-150e7d470369"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6223"
                        },
                        new
                        {
                            Id = new Guid("d8adce02-94a1-46b6-b0d2-405ffb9aa06e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6224"
                        },
                        new
                        {
                            Id = new Guid("d045e1a1-ec32-4a3f-9102-9b0918f2e1ae"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6225"
                        },
                        new
                        {
                            Id = new Guid("fa983b50-41b5-4ab7-adf6-f816be20395d"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6226"
                        },
                        new
                        {
                            Id = new Guid("f5dfbc4b-c1bc-4ba4-874f-6809a03342fd"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6227"
                        },
                        new
                        {
                            Id = new Guid("f5177978-b80c-481d-ae26-186ee5b009a7"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6228"
                        },
                        new
                        {
                            Id = new Guid("c9231aba-0ace-4dd1-b866-f1321282e05f"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62290"
                        },
                        new
                        {
                            Id = new Guid("f1ba3ab3-eae9-4086-90c8-0b5f3ef70fa4"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62291"
                        },
                        new
                        {
                            Id = new Guid("3496fd21-a699-4136-9138-58cbf5c58022"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622920"
                        },
                        new
                        {
                            Id = new Guid("f98fdbbb-5951-4581-bead-52afffbfa96b"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622921"
                        },
                        new
                        {
                            Id = new Guid("22312464-a6e6-4ac5-a22d-11f3239c236d"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622922"
                        },
                        new
                        {
                            Id = new Guid("52d7222a-5e9b-4a01-be92-2cc239449f09"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622923"
                        },
                        new
                        {
                            Id = new Guid("95b4e502-a5e0-4d19-96c3-fdea0c4246d2"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622924"
                        },
                        new
                        {
                            Id = new Guid("303fecf6-07f6-49fd-b130-7754381ba3a5"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622925"
                        },
                        new
                        {
                            Id = new Guid("d25a8d96-b8b6-4e83-837d-ffdee9d0314e"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "627780"
                        },
                        new
                        {
                            Id = new Guid("d156efbf-3c80-4654-b512-9e8544f7d173"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "67410"
                        },
                        new
                        {
                            Id = new Guid("f53a92e3-6a45-44dc-a7e6-f30c6df6b4f9"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "111111"
                        },
                        new
                        {
                            Id = new Guid("c24c41b4-5fa8-489e-a490-3626916aed04"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "506874"
                        },
                        new
                        {
                            Id = new Guid("cb90d1f2-768b-445c-8a63-f20591bd5e2e"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "640485"
                        },
                        new
                        {
                            Id = new Guid("91475940-8275-45a4-b541-84c3a573f4ac"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509093"
                        },
                        new
                        {
                            Id = new Guid("7ac13fff-0453-44a8-8af0-da3b4aea8e14"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650042"
                        },
                        new
                        {
                            Id = new Guid("ec8cade7-e96f-4d63-8119-14bb9f57b847"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("98cfde2c-73d7-410e-abe1-11ec07995bf6"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("fa547b11-ce6f-48cd-80da-0e60fd688803"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509005"
                        },
                        new
                        {
                            Id = new Guid("a04042b2-6d1e-4939-b771-8fbe157e6277"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650920"
                        },
                        new
                        {
                            Id = new Guid("7cdfb881-bbde-4835-a641-dedf9a53ce88"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "699988"
                        },
                        new
                        {
                            Id = new Guid("edd4843a-0241-4b16-b9f3-1d538a05419b"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "508757"
                        },
                        new
                        {
                            Id = new Guid("82367ba3-735b-4ae4-a6dd-3ff197204db4"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "680405"
                        },
                        new
                        {
                            Id = new Guid("403cdeab-2262-43ba-8291-4b6eb8069521"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509423"
                        },
                        new
                        {
                            Id = new Guid("39bfb275-75cf-4f7f-a636-998cd110d5e2"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6538"
                        },
                        new
                        {
                            Id = new Guid("05c93df6-fa45-4ddd-af60-5cff4acb9261"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509156"
                        },
                        new
                        {
                            Id = new Guid("2a64a61c-74f9-4559-8d3c-98e8ef70b968"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509284"
                        },
                        new
                        {
                            Id = new Guid("5f31dd25-27db-4bf3-bf05-89fb535c4b87"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "502577"
                        },
                        new
                        {
                            Id = new Guid("d6251d2e-565a-4dbd-b3db-e6dab45abd64"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509004"
                        },
                        new
                        {
                            Id = new Guid("048d4fa1-5fff-43b0-becf-c5cf3985f288"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509294"
                        },
                        new
                        {
                            Id = new Guid("88f3d8ac-c199-4241-9f09-8e7cbb056ebf"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509730"
                        },
                        new
                        {
                            Id = new Guid("ce6d9e37-985d-4679-8884-9c8c806c325e"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509010"
                        },
                        new
                        {
                            Id = new Guid("bf283f74-b125-4638-8abb-dc79ed838347"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6509"
                        },
                        new
                        {
                            Id = new Guid("1c9979a2-e1f7-4e15-a1e4-0476746eed26"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "6507"
                        },
                        new
                        {
                            Id = new Guid("f98ed4ec-c970-4977-a143-a0b0ac8bb944"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "650914"
                        },
                        new
                        {
                            Id = new Guid("e993c560-70ac-4b38-9e02-bc556776c6a9"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "509274"
                        },
                        new
                        {
                            Id = new Guid("903a59f0-5174-43d3-bb15-bc945a1cb947"),
                            Brand = "ELO",
                            Order = 4,
                            Prefix = "506741"
                        },
                        new
                        {
                            Id = new Guid("5384e93c-9d3d-4eee-9718-b4c824deb41a"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6505"
                        },
                        new
                        {
                            Id = new Guid("e2ab1c80-8fa3-4316-bd27-6c754db0a263"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6280"
                        },
                        new
                        {
                            Id = new Guid("945975b4-c869-4ee5-8a54-ed664a0a7092"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6504"
                        },
                        new
                        {
                            Id = new Guid("a07277cc-e441-413b-8554-31d99cc02c61"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6550"
                        },
                        new
                        {
                            Id = new Guid("bfe6cec8-639d-4208-901d-a4b325c51e61"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "509023"
                        },
                        new
                        {
                            Id = new Guid("0408c5f1-35ee-4a11-8c5f-86bbc51c845e"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6516"
                        },
                        new
                        {
                            Id = new Guid("205b2eda-3c00-41c3-8f88-4d05c385c72b"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650507"
                        },
                        new
                        {
                            Id = new Guid("098048d4-5b95-4d37-9bac-e4a0f1d157a3"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "636368"
                        },
                        new
                        {
                            Id = new Guid("c03ac10f-7e5d-483d-bd32-6d048971ffd9"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "438935"
                        },
                        new
                        {
                            Id = new Guid("24942dd0-ed48-457a-95d6-a095c697555b"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "504175"
                        },
                        new
                        {
                            Id = new Guid("07220f86-40c3-4cf8-b808-8f2ff71ed1fb"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "451416"
                        },
                        new
                        {
                            Id = new Guid("d7941097-958e-4415-a812-4e06ef8b6856"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("f8b906d8-90a5-452f-89b7-6b545ae9d862"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509067"
                        },
                        new
                        {
                            Id = new Guid("659cb6ca-ba9c-41e2-89ee-e6ce1edbb831"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509049"
                        },
                        new
                        {
                            Id = new Guid("b0ad50ec-ad85-4522-90d5-a8bc5a665107"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509069"
                        },
                        new
                        {
                            Id = new Guid("57054b54-2b5b-410b-9dff-e7a8f89a0a6d"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509050"
                        },
                        new
                        {
                            Id = new Guid("5d38ad8f-caec-4857-b133-a706e4626c2a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509074"
                        },
                        new
                        {
                            Id = new Guid("1952ec49-7875-4b40-8add-56096f303527"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50906"
                        },
                        new
                        {
                            Id = new Guid("dfac0de8-9c0d-4aa5-b1c7-df2b3fa4b3f5"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("160a7892-5bfc-469f-a7ab-7b936c581b87"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509045"
                        },
                        new
                        {
                            Id = new Guid("ff84d469-644d-4cda-a689-c52b23544007"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509051"
                        },
                        new
                        {
                            Id = new Guid("99d5fa65-a08e-4722-a972-a23e0b1f1bce"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509046"
                        },
                        new
                        {
                            Id = new Guid("2079b6de-05eb-41dd-9ba2-0b6af151f4f7"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509066"
                        },
                        new
                        {
                            Id = new Guid("f4469007-7a5d-4c3a-b677-99781db4ce01"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("d420ba9d-d31c-4951-9ca0-4b5ae1c8e3c9"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509042"
                        },
                        new
                        {
                            Id = new Guid("509a4f19-82b9-4d75-88ef-d84ebd16781a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509052"
                        },
                        new
                        {
                            Id = new Guid("eaf2526b-34e1-4aad-b6c1-ef6e944db47f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509043"
                        },
                        new
                        {
                            Id = new Guid("1823e450-8874-4cc1-9de4-08523b8a4f3f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509064"
                        },
                        new
                        {
                            Id = new Guid("40452bdf-a81f-4366-85fa-ebb00b013d2c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("79f2ef93-1804-459b-8147-4c3fa8db191f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "36297"
                        },
                        new
                        {
                            Id = new Guid("c856a63e-8489-4ddc-8ce4-aa86835cd54c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "5067"
                        },
                        new
                        {
                            Id = new Guid("82e81022-111f-49a2-aac3-43691f62cb53"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4576"
                        },
                        new
                        {
                            Id = new Guid("bea36cbc-dc2a-4275-8cf3-2d121ace428b"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4011"
                        },
                        new
                        {
                            Id = new Guid("d047e37d-63bb-438d-ae24-044c21817612"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509000"
                        },
                        new
                        {
                            Id = new Guid("e9ac6cfc-bced-4e62-9eef-863b1e710193"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650905"
                        },
                        new
                        {
                            Id = new Guid("2e241a05-fc6b-4168-956e-3475acb11b4a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650494"
                        },
                        new
                        {
                            Id = new Guid("1316f48d-45a0-422c-8052-194cc4058f17"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650485"
                        },
                        new
                        {
                            Id = new Guid("061ae4df-537e-4172-95c0-0e4ddf47c2ab"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509091"
                        },
                        new
                        {
                            Id = new Guid("cd25a2d3-cb26-437c-a641-d78ae058e398"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650491"
                        },
                        new
                        {
                            Id = new Guid("2310ce2a-0cef-4e59-abad-9151ab7f8f86"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "65090"
                        },
                        new
                        {
                            Id = new Guid("1500bd31-b2fe-4d46-bec1-e7404593cc77"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650487"
                        },
                        new
                        {
                            Id = new Guid("b90bed1e-eb1a-415d-9830-ed8762322a1a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "409835"
                        },
                        new
                        {
                            Id = new Guid("51fc59fa-38ed-475e-bfa3-7ef22efd197f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("3868ef5b-44f4-48aa-a991-27b67178233f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650921"
                        },
                        new
                        {
                            Id = new Guid("632cd6db-9c30-4a66-b787-3b9dbcd36ed8"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650912"
                        },
                        new
                        {
                            Id = new Guid("815bb75c-5a19-4f9c-8e46-18e3eb2124cb"),
                            Brand = "HIPERCARD",
                            Order = 0,
                            Prefix = "506282"
                        },
                        new
                        {
                            Id = new Guid("614b0a37-52dc-49ac-85d1-9110b54cd8de"),
                            Brand = "HIPERCARD",
                            Order = 60,
                            Prefix = "38"
                        },
                        new
                        {
                            Id = new Guid("088760b9-e4d1-4d2f-b3b1-fcb46ff3db1c"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "606282"
                        },
                        new
                        {
                            Id = new Guid("92d42519-20c2-4511-88f8-e885035a5544"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "3841"
                        },
                        new
                        {
                            Id = new Guid("1267b22c-c2e0-497d-a7d5-9273d825e2ee"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "2131"
                        },
                        new
                        {
                            Id = new Guid("2f31117e-0f1f-4c3a-ae85-6292677e20c4"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "1800"
                        },
                        new
                        {
                            Id = new Guid("8f04b17b-4c9d-47ce-836a-67dc1db40b1a"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("01dd051b-9748-447b-b18c-7c09d5b97ea4"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "546479"
                        },
                        new
                        {
                            Id = new Guid("dad6fddf-43e4-4e41-8a7f-7599818f84c6"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("31466289-a64f-4ef4-8048-6a7b863384ad"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "589916"
                        },
                        new
                        {
                            Id = new Guid("75e450fa-fce8-4520-b33b-7e882c9d685f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "585988"
                        },
                        new
                        {
                            Id = new Guid("4e44f826-0905-4c14-9570-667f45314af9"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("9e48b628-c17d-415c-825c-7ab63abc1158"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "439133"
                        },
                        new
                        {
                            Id = new Guid("5ba8cd2b-160e-4ddb-9d9e-561d2f9ebc9b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "55909"
                        },
                        new
                        {
                            Id = new Guid("e7b7774e-5cf7-4b74-880b-fbeda90773c3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "53508"
                        },
                        new
                        {
                            Id = new Guid("b062ccbd-f8ae-42d4-a036-93ffd390d483"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "320132"
                        },
                        new
                        {
                            Id = new Guid("65f70d51-92ff-4618-9012-ce798659818b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "126820"
                        },
                        new
                        {
                            Id = new Guid("a7c26d98-1469-4753-8eb9-25022d98ca98"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576292"
                        },
                        new
                        {
                            Id = new Guid("3a680ea8-9065-4cef-ad90-f945f7de4ad8"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5453"
                        },
                        new
                        {
                            Id = new Guid("f54543bd-b62a-4605-8198-3775850f350b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5379"
                        },
                        new
                        {
                            Id = new Guid("027b4a74-656d-46c6-ab8a-9cdfcd7e7840"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "537993"
                        },
                        new
                        {
                            Id = new Guid("0ebcb56a-2f6a-4a1a-8968-567e8cbdfa9b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "639350"
                        },
                        new
                        {
                            Id = new Guid("1c4ad172-a014-45ef-903d-408e79b602cc"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "830050"
                        },
                        new
                        {
                            Id = new Guid("7a921757-5c3d-4a5c-92f4-ffb9d1a73d15"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "517349"
                        },
                        new
                        {
                            Id = new Guid("3c897b37-f1f7-41b6-8808-00e4fd6db6c1"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("13330e1d-0cbd-489e-b6f9-e1ed7e1a341a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560033"
                        },
                        new
                        {
                            Id = new Guid("68b87a6f-dd97-4a42-8d32-21d5d58ac7d8"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505381"
                        },
                        new
                        {
                            Id = new Guid("c1263f10-5c1b-4a2b-b05e-689cb4d96b3d"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("95e8bd16-68ac-43d1-9bc8-7f1d4469fdfb"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "595922"
                        },
                        new
                        {
                            Id = new Guid("ae99dfec-3235-476e-90ac-184f0303d2e3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("a8bdc9f1-83b6-4680-85e5-faf1d5f3972a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "7807"
                        },
                        new
                        {
                            Id = new Guid("0dede810-1393-4184-9d29-809226dc821e"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509257"
                        },
                        new
                        {
                            Id = new Guid("d60c7d36-5b82-44e8-a20c-7090b14760a4"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502309"
                        },
                        new
                        {
                            Id = new Guid("a3c2c1f4-8dde-402a-b7ff-68872be45c50"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "212743"
                        },
                        new
                        {
                            Id = new Guid("b31e9b1a-ce6f-4420-8793-033e10c7ac3a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505316"
                        },
                        new
                        {
                            Id = new Guid("0e736326-f548-4441-a03c-080e1592de58"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "720358"
                        },
                        new
                        {
                            Id = new Guid("f3a08d27-a025-4033-881e-76f63c0069d3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502299"
                        },
                        new
                        {
                            Id = new Guid("d793b0aa-79ed-43b2-bb4d-fd59fd829e62"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "330239"
                        },
                        new
                        {
                            Id = new Guid("059ac16b-97f2-40fb-9fab-f5941b086a6c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "640245"
                        },
                        new
                        {
                            Id = new Guid("51abab36-4a14-46a5-a2fe-2ccb6ce57a72"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "3006"
                        },
                        new
                        {
                            Id = new Guid("575fd7a7-cbaf-4b5e-b65b-20c8c6a0b00c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "615292"
                        },
                        new
                        {
                            Id = new Guid("4e7bb92d-c26f-4b84-99fc-e2d68abc7446"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "574080"
                        },
                        new
                        {
                            Id = new Guid("b6e31761-9896-4ed2-86ce-af5f18646d38"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "608710"
                        },
                        new
                        {
                            Id = new Guid("76e5495b-1c3a-4ce2-9a45-145fde4e509a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "507641"
                        },
                        new
                        {
                            Id = new Guid("3865bdf2-3641-4d89-a810-ee32ed6265a5"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "316811"
                        },
                        new
                        {
                            Id = new Guid("c763250f-ed31-4e6b-ba19-c965fdb9cea7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "569970"
                        },
                        new
                        {
                            Id = new Guid("fb746902-bd84-49e6-8d7a-3b0fdaf16c76"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960397"
                        },
                        new
                        {
                            Id = new Guid("6f93f2a0-bad8-4855-9c8a-9f3559e3a9bf"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "220209"
                        },
                        new
                        {
                            Id = new Guid("c595eb0b-ac0a-45f3-bd9e-5b81111adc2a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "637095"
                        },
                        new
                        {
                            Id = new Guid("a483349d-23b1-4efb-85ca-3bb912a3becb"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576096"
                        },
                        new
                        {
                            Id = new Guid("703cc93b-eb8e-4ce3-b4ed-752fca750c98"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "596497"
                        },
                        new
                        {
                            Id = new Guid("08f0118f-01a3-40ea-8a7a-87b7f0dde3cb"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "570209"
                        },
                        new
                        {
                            Id = new Guid("b0f9f7cc-df93-46ff-b0be-8688a941c940"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "44027"
                        },
                        new
                        {
                            Id = new Guid("61f52435-4e56-4461-90dc-4fdfe91dd708"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960379"
                        },
                        new
                        {
                            Id = new Guid("a1256b81-5da8-44f0-b6e4-4a07a0d1a8e5"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "608783"
                        },
                        new
                        {
                            Id = new Guid("41f8227b-2018-4bc8-9be7-33e879231c6a"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "750209"
                        },
                        new
                        {
                            Id = new Guid("d716abff-488f-4ea0-9508-fbebbf05fddb"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "515894"
                        },
                        new
                        {
                            Id = new Guid("6898476d-4a09-4f0c-9911-ed18b86e97f7"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2221"
                        },
                        new
                        {
                            Id = new Guid("8fdaecd6-eee1-4177-91ca-94996b9c08a2"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2222"
                        },
                        new
                        {
                            Id = new Guid("5477e2e8-99a5-421c-bc51-befcef0a3e0d"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2223"
                        },
                        new
                        {
                            Id = new Guid("cb148a01-163a-4418-9f84-4079d1e73c20"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2224"
                        },
                        new
                        {
                            Id = new Guid("bc676852-e91d-460d-a807-1b4bcf307f12"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2225"
                        },
                        new
                        {
                            Id = new Guid("b14b8f2d-beed-483e-9d26-8fd88665fe4a"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2226"
                        },
                        new
                        {
                            Id = new Guid("a90a56f9-c6b0-4f71-a20a-27a6a572da42"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2227"
                        },
                        new
                        {
                            Id = new Guid("0e1d995e-72e5-429f-b5bd-2771c5e258aa"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2228"
                        },
                        new
                        {
                            Id = new Guid("c87a9cb4-99d3-4e8d-a24d-9dd3c6eaa7c9"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2229"
                        },
                        new
                        {
                            Id = new Guid("f22d4fbc-1817-4708-a625-3c3f382b07ba"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "223"
                        },
                        new
                        {
                            Id = new Guid("54eb1635-6a00-4f52-bef2-684a1b26ecda"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "224"
                        },
                        new
                        {
                            Id = new Guid("7e9a101e-dfe7-4298-a4a2-387aa3b80c64"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "225"
                        },
                        new
                        {
                            Id = new Guid("5d960482-3969-4c87-be29-17d5c43a2e55"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "226"
                        },
                        new
                        {
                            Id = new Guid("d3c145fc-4ef5-4071-9453-f55860569fbe"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "227"
                        },
                        new
                        {
                            Id = new Guid("33e22d21-5b1e-42bb-a904-0863a0f5a0b0"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "228"
                        },
                        new
                        {
                            Id = new Guid("cabdec57-49b3-45a9-bacd-8a6f03dfc301"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "229"
                        },
                        new
                        {
                            Id = new Guid("e2c4c2cf-b9eb-43bf-8209-72f3a914c884"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "23"
                        },
                        new
                        {
                            Id = new Guid("7a0523bd-735c-417f-bad1-27ad67d1ac43"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "24"
                        },
                        new
                        {
                            Id = new Guid("0103cc08-7c06-4484-82d1-a6f5053d604a"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "25"
                        },
                        new
                        {
                            Id = new Guid("e1766abc-6e9b-4fcf-aa65-b391825ebbef"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "26"
                        },
                        new
                        {
                            Id = new Guid("be546703-a100-4bef-838d-69049919cf6f"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "271"
                        },
                        new
                        {
                            Id = new Guid("c231fabb-2877-4539-8d46-c116e1ebe5a0"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2720"
                        },
                        new
                        {
                            Id = new Guid("12104118-8715-4c7a-8a09-f618be1681fb"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "51"
                        },
                        new
                        {
                            Id = new Guid("2068770b-7b3e-423a-9e9f-f5806af532a4"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "52"
                        },
                        new
                        {
                            Id = new Guid("66c74f33-b738-4c2e-bd24-dc6a63b7e3aa"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "53"
                        },
                        new
                        {
                            Id = new Guid("d442fb00-ca4d-4fd5-8445-4d7d17b828e1"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "54"
                        },
                        new
                        {
                            Id = new Guid("c8b94981-985a-4429-b2d4-ffb052a5d874"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "55"
                        },
                        new
                        {
                            Id = new Guid("6de3804d-4ce7-4435-aeb5-4258771a3d9d"),
                            Brand = "NARANJA E NEVADA",
                            Order = 100,
                            Prefix = "589562"
                        },
                        new
                        {
                            Id = new Guid("da38e5da-6062-44ab-ba6b-e63676f8285a"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "627892"
                        },
                        new
                        {
                            Id = new Guid("c1f1facb-eb39-4e46-aa9b-24cc89958e02"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("9b4c2e5e-47a8-44e5-8af7-d9c737900528"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "121772"
                        },
                        new
                        {
                            Id = new Guid("5f6b3239-1fcd-4bba-b9e5-08d431c0405e"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "40064"
                        },
                        new
                        {
                            Id = new Guid("a299b9b1-a0f4-46da-8c52-f815b50d835b"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "444125"
                        },
                        new
                        {
                            Id = new Guid("34ad1e86-756a-49f1-8cf6-d144eb637ae4"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "798431"
                        },
                        new
                        {
                            Id = new Guid("892cf9af-6071-4c19-9f4d-769ab3a43bf0"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "48546"
                        },
                        new
                        {
                            Id = new Guid("fd364ef7-5e1d-4006-a790-76192a84ca55"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "988442"
                        },
                        new
                        {
                            Id = new Guid("da4daec6-963a-4654-ae13-bc4b99654d1c"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("54283d8d-6149-4d71-8aab-978dcf7cfcd6"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("ab9fbafd-dfcf-4f93-91bf-3ce3b5af8e3a"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("bd245a24-6d66-4e49-b472-47de7223197d"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "984428"
                        },
                        new
                        {
                            Id = new Guid("e65e5c8e-0576-4e1c-8629-7535c996bebb"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "636355"
                        },
                        new
                        {
                            Id = new Guid("b7953602-f2c7-45aa-8ab2-6de218052755"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "27728"
                        },
                        new
                        {
                            Id = new Guid("b999fbc9-b7ff-43a8-9070-b34dc0535fec"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "107915"
                        },
                        new
                        {
                            Id = new Guid("ec902657-8095-4a27-8b30-329f6790c944"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "210790"
                        },
                        new
                        {
                            Id = new Guid("78ff5b1b-57eb-4ce2-88f3-fbf236e18279"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "854644"
                        },
                        new
                        {
                            Id = new Guid("61db91b8-953a-4734-bad9-3d1bcf98b22b"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "33994"
                        },
                        new
                        {
                            Id = new Guid("481ea7cf-0931-4f88-b61a-109cf23a17af"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "985966"
                        },
                        new
                        {
                            Id = new Guid("6ef6af52-2f75-432c-a125-f93f2b4806b7"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "960421"
                        },
                        new
                        {
                            Id = new Guid("d54591b8-2886-47b8-ae6f-6033b3839d48"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "186307"
                        },
                        new
                        {
                            Id = new Guid("5e4a1ae8-f398-409a-93e1-435a0f0cac27"),
                            Brand = "VISA",
                            Order = 5,
                            Prefix = "4984"
                        },
                        new
                        {
                            Id = new Guid("8ef050ac-1ed8-43ca-9633-3a02549f2bfb"),
                            Brand = "VISA",
                            Order = 110,
                            Prefix = "4"
                        });
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BraspagProvider")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("FeevCheckout.Models.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankAgency")
                        .HasColumnType("text");

                    b.Property<string>("BankNumber")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CheckingAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.Property<JsonDocument>("Response")
                        .HasColumnType("jsonb");

                    b.Property<PaymentAttemptStatus>("Status")
                        .HasColumnType("payment_attempt_status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("TransactionId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SuccessfulPaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("SuccessfulPaymentAttemptId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany("Products")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.PaymentAttempt", "SuccessfulPaymentAttempt")
                        .WithMany()
                        .HasForeignKey("SuccessfulPaymentAttemptId");

                    b.OwnsOne("FeevCheckout.Models.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Document")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerDocument");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerName");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("FeevCheckout.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("CustomerTransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressCity");

                                    b2.Property<string>("Complement")
                                        .HasColumnType("text");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressUF");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressStreet");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressPostalCode");

                                    b2.HasKey("CustomerTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerTransactionId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("SuccessfulPaymentAttempt");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
