// <auto-generated />
using System;
using System.Text.Json;
using FeevCheckout.Data;
using FeevCheckout.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeevCheckout.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128161351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_attempt_status", new[] { "pending", "created", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "feev_pix", "feev_boleto", "braspag_cartao" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeevCheckout.Models.CardBrandPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardBrandPatterns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2dd52bd-da7c-4d38-a3fe-6595835fbe9d"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "34"
                        },
                        new
                        {
                            Id = new Guid("5127c77a-e485-474e-865f-d55d16104090"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("b1e470be-3bb1-4cd0-ade8-4f9fa46c2a3a"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("2455bd06-47c5-4b20-a22b-b77010f9386e"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "37"
                        },
                        new
                        {
                            Id = new Guid("f4db535d-ce27-4ebe-8d01-9771b81b0c11"),
                            Brand = "CABAL",
                            Order = 60,
                            Prefix = "6042"
                        },
                        new
                        {
                            Id = new Guid("bce2bf7f-e123-483a-9ec2-9f1265c81f69"),
                            Brand = "DINERS",
                            Order = 0,
                            Prefix = "605919"
                        },
                        new
                        {
                            Id = new Guid("04029e09-c56a-4849-946b-cffb23e8dbb4"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "300"
                        },
                        new
                        {
                            Id = new Guid("cd33e4b6-ffd7-48f5-bf7a-33d9a1416655"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "301"
                        },
                        new
                        {
                            Id = new Guid("9f3280c6-280e-40d2-a92b-bbe3d2b7e1cd"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "302"
                        },
                        new
                        {
                            Id = new Guid("ffdc5e98-c34f-46c7-89c6-ef762b6e53eb"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "303"
                        },
                        new
                        {
                            Id = new Guid("4993c42d-cef1-40d6-a5d3-5ba3b41a3f9f"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "304"
                        },
                        new
                        {
                            Id = new Guid("a455223d-54e5-4459-8c0f-1d8a62481346"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "305"
                        },
                        new
                        {
                            Id = new Guid("894cc484-c9af-4cec-8f05-681be73a7994"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("1895b3bf-ecc6-42c4-bb1f-5402b6aa9d62"),
                            Brand = "DISCOVER",
                            Order = 1,
                            Prefix = "306262"
                        },
                        new
                        {
                            Id = new Guid("377446b9-fd5b-484c-b0b0-71f5b5eec73a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6011"
                        },
                        new
                        {
                            Id = new Guid("eafb8d4a-2fdc-454e-a659-0ae822e64022"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "65"
                        },
                        new
                        {
                            Id = new Guid("1c84372b-2eee-4414-a07b-e912581da602"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "644"
                        },
                        new
                        {
                            Id = new Guid("36de40c9-b74e-4d55-ab5a-82b4e2b6ff47"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "645"
                        },
                        new
                        {
                            Id = new Guid("b6f7207a-21b9-4fb0-81e9-3e55d77ddfcf"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "646"
                        },
                        new
                        {
                            Id = new Guid("59057700-ef58-4bd6-a2e0-c0be0985db07"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "647"
                        },
                        new
                        {
                            Id = new Guid("2981e6f9-3475-44af-ad56-2af0d52bce8a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "648"
                        },
                        new
                        {
                            Id = new Guid("cd5a8a4d-3fe5-46c8-9bf4-ff632ed4a3e7"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "649"
                        },
                        new
                        {
                            Id = new Guid("bb547111-3fa8-496a-8852-45a2e19eaf5e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622126"
                        },
                        new
                        {
                            Id = new Guid("fe106cea-d47a-4744-aaeb-eeaac4c1297d"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622127"
                        },
                        new
                        {
                            Id = new Guid("215d0f4e-6f46-4c1a-8018-87d143b4baea"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622128"
                        },
                        new
                        {
                            Id = new Guid("5f23e025-81db-445a-810b-c2d89c3b0d21"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622129"
                        },
                        new
                        {
                            Id = new Guid("ddbf27fc-21d8-444c-b93b-47a6f713bcf6"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62213"
                        },
                        new
                        {
                            Id = new Guid("4eaf9524-7252-4b25-8a24-071a8d979413"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62214"
                        },
                        new
                        {
                            Id = new Guid("b11ac102-5dfd-4b8b-a4e8-d0e9204436fb"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62215"
                        },
                        new
                        {
                            Id = new Guid("2e32e13e-f65b-4c43-b439-e497b7ffaa57"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62216"
                        },
                        new
                        {
                            Id = new Guid("2ebd5eaf-c805-4446-b317-4f5f755136c8"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62217"
                        },
                        new
                        {
                            Id = new Guid("5b204185-88c2-4e16-a7b8-ce96e52d5779"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62218"
                        },
                        new
                        {
                            Id = new Guid("266c0ebf-210d-4c33-8b45-fe2f7edd6fd3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62219"
                        },
                        new
                        {
                            Id = new Guid("e1f7e6f5-13e6-4b66-ad5c-5b66ed179356"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6222"
                        },
                        new
                        {
                            Id = new Guid("1ea5f343-1f19-4c43-a9f5-a2a3adbbb6dc"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6223"
                        },
                        new
                        {
                            Id = new Guid("baa161f5-9fac-408f-a32e-4b4492924167"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6224"
                        },
                        new
                        {
                            Id = new Guid("6479e443-5840-4b6d-ac0a-f3ad0ce80e4d"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6225"
                        },
                        new
                        {
                            Id = new Guid("2139bc42-1b72-4dfd-bf7e-157c7a167649"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6226"
                        },
                        new
                        {
                            Id = new Guid("82be5869-6fee-4782-8961-024a1e2473e7"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6227"
                        },
                        new
                        {
                            Id = new Guid("93699de3-edd6-4024-a5a7-bf8f936ca867"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6228"
                        },
                        new
                        {
                            Id = new Guid("fa03dcfd-1f17-44b9-aa39-433ea948bfa3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62290"
                        },
                        new
                        {
                            Id = new Guid("fe1a8677-1d09-459a-803d-e08ada083a65"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62291"
                        },
                        new
                        {
                            Id = new Guid("8a456406-2c12-4a59-8ea5-0e2454f71796"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622920"
                        },
                        new
                        {
                            Id = new Guid("baebd91b-9623-4260-ad5b-af4662a10b96"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622921"
                        },
                        new
                        {
                            Id = new Guid("f5c201c3-4cd1-4844-b1bf-ac72986cd43a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622922"
                        },
                        new
                        {
                            Id = new Guid("b661f15e-c32d-4b24-980d-8b2f9f90dbe4"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622923"
                        },
                        new
                        {
                            Id = new Guid("7d440ed1-d01c-481e-b517-05b8cc76c579"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622924"
                        },
                        new
                        {
                            Id = new Guid("6c5a79b4-b41e-4b92-acf0-92a6b55abd36"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622925"
                        },
                        new
                        {
                            Id = new Guid("1bd1b2df-f667-4853-b4ad-2c7ff84a039e"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "627780"
                        },
                        new
                        {
                            Id = new Guid("cb530f63-d672-49f9-b90e-198c1730c4a4"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "67410"
                        },
                        new
                        {
                            Id = new Guid("cdce4927-80a9-4b6d-9438-56def8a2b1e6"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "111111"
                        },
                        new
                        {
                            Id = new Guid("c1acc363-7ccd-4f43-909c-2796f86f6811"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "506874"
                        },
                        new
                        {
                            Id = new Guid("40dade13-2d20-4f0e-8496-1a84dfd86181"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "640485"
                        },
                        new
                        {
                            Id = new Guid("1f3a9016-d24b-4c38-8bb0-1ef5db7a6656"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509093"
                        },
                        new
                        {
                            Id = new Guid("22920e15-13f2-4985-adfd-513eb097aaa3"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650042"
                        },
                        new
                        {
                            Id = new Guid("e274cbf7-4c1a-4553-b470-c571ecd1f416"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("ed68f39d-f946-4af2-9dcd-a4b7056cae78"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509005"
                        },
                        new
                        {
                            Id = new Guid("dd59877d-b1d8-4aa4-b2f2-dee2992c11fa"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650920"
                        },
                        new
                        {
                            Id = new Guid("bd829626-5c9a-4f14-aa24-46be950051ea"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "699988"
                        },
                        new
                        {
                            Id = new Guid("85eac545-decc-4313-a84b-055ec3eb30b7"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "508757"
                        },
                        new
                        {
                            Id = new Guid("1226024e-da5b-4ecb-b22b-2e5ccf10e759"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "680405"
                        },
                        new
                        {
                            Id = new Guid("0a40107f-db62-41eb-a507-dd13a6c9dbfc"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509423"
                        },
                        new
                        {
                            Id = new Guid("5bde3090-6f6e-43e1-b316-3851f8b0e591"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "006538"
                        },
                        new
                        {
                            Id = new Guid("d373b40b-66fa-451b-b5a8-965086723752"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509156"
                        },
                        new
                        {
                            Id = new Guid("f128d9c6-a1e8-49c5-b4e1-7ed6ec5dfa49"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509284"
                        },
                        new
                        {
                            Id = new Guid("713fd508-c89b-4894-b9f5-809792cced74"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "502577"
                        },
                        new
                        {
                            Id = new Guid("3d2d694d-3d71-4bb3-a358-ddfeb99988e2"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509004"
                        },
                        new
                        {
                            Id = new Guid("61b0ece5-f43f-4bdb-ab94-73ced9107144"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509294"
                        },
                        new
                        {
                            Id = new Guid("56c99f1f-5063-402b-9b37-db9e2cdda98e"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509730"
                        },
                        new
                        {
                            Id = new Guid("f6e69e5d-3940-4afb-ad48-b2932e075031"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509010"
                        },
                        new
                        {
                            Id = new Guid("3c95709d-5f6e-4d3f-95b2-b6d4cb98b074"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6509"
                        },
                        new
                        {
                            Id = new Guid("3b2e392f-8aba-47cb-b38e-6a9783f9c66c"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "6507"
                        },
                        new
                        {
                            Id = new Guid("d2076b08-7e08-4cc6-a533-37e6eccfd9fc"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "650914"
                        },
                        new
                        {
                            Id = new Guid("571ca1dc-63ed-4d4d-bbfe-c00560fe4c08"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "509274"
                        },
                        new
                        {
                            Id = new Guid("67c21260-6e79-45bd-9f4d-ff6b64bbf5d8"),
                            Brand = "ELO",
                            Order = 4,
                            Prefix = "506741"
                        },
                        new
                        {
                            Id = new Guid("919a9134-b3b9-4bf1-9fa0-48e507deb47b"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6505"
                        },
                        new
                        {
                            Id = new Guid("d0a80bae-3f0b-4519-bb13-3619262398a2"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6280"
                        },
                        new
                        {
                            Id = new Guid("e1e68a6e-3d21-4466-a014-a12cd6da4514"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6504"
                        },
                        new
                        {
                            Id = new Guid("bf4969cb-fb5f-4000-8e12-e318d567a0d9"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6550"
                        },
                        new
                        {
                            Id = new Guid("7342fa6e-e737-45b3-8844-d85298e7975e"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "509023"
                        },
                        new
                        {
                            Id = new Guid("6fc94aa9-eb2b-43eb-b2dd-87dd5361f16d"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6516"
                        },
                        new
                        {
                            Id = new Guid("e7d74a25-fed9-4d49-96d9-ec4b6d4a3891"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650507"
                        },
                        new
                        {
                            Id = new Guid("2c78ebae-3891-4cd6-986b-e80fe208845c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "636368"
                        },
                        new
                        {
                            Id = new Guid("debdbe26-833d-47f6-9de6-d10fbe2af90a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "438935"
                        },
                        new
                        {
                            Id = new Guid("747ece4d-43a5-4793-b659-b3f11c7c7ada"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "504175"
                        },
                        new
                        {
                            Id = new Guid("a0cef9b0-5c2c-4966-a242-39ccaa9f1dd2"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "451416"
                        },
                        new
                        {
                            Id = new Guid("a5efa71d-7ce2-462b-ba32-e6b0bb6115c1"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("8d9cd703-0c4f-42b0-8914-2168189ee0fd"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509067"
                        },
                        new
                        {
                            Id = new Guid("51928f8d-621a-4b00-b6fe-dcd956dbe528"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509049"
                        },
                        new
                        {
                            Id = new Guid("75dfd39f-8703-44e1-a04f-7e4b985f0159"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509069"
                        },
                        new
                        {
                            Id = new Guid("83e0cf28-f802-4254-aa1b-1ced172edab6"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509050"
                        },
                        new
                        {
                            Id = new Guid("39a3fb06-b3c5-4148-8251-88105679e9ed"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509074"
                        },
                        new
                        {
                            Id = new Guid("a8b85150-056a-453a-8678-c8d10779d5a1"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50906"
                        },
                        new
                        {
                            Id = new Guid("4ffe5519-7875-4e23-83e2-105477206428"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("32e917d9-4b27-4e4e-8ede-e4bd461d8f03"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509045"
                        },
                        new
                        {
                            Id = new Guid("09c81bd9-0a53-49f3-af35-7c521df59943"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509051"
                        },
                        new
                        {
                            Id = new Guid("0d537f7f-7bbb-4125-ba56-464212680857"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509046"
                        },
                        new
                        {
                            Id = new Guid("a578ec2e-2492-4c6e-a783-8b5f928cac5a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509066"
                        },
                        new
                        {
                            Id = new Guid("ede7ea0e-8df3-465d-85e9-fb0671743b01"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509042"
                        },
                        new
                        {
                            Id = new Guid("e07c6274-1a20-4b3b-9c3b-23ed9a4de815"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509052"
                        },
                        new
                        {
                            Id = new Guid("a1b1e2b6-ac4c-44ef-9f9b-482efef3f410"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509043"
                        },
                        new
                        {
                            Id = new Guid("033d4215-1800-410c-b309-5020a550c571"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509064"
                        },
                        new
                        {
                            Id = new Guid("34d2dd63-540d-402a-bb0b-62cf9dabd64e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("9c846466-addc-44a5-a9e9-c0d9ce6c6c55"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "36297"
                        },
                        new
                        {
                            Id = new Guid("42e1eec8-bbcc-494e-bbed-00f938e97d1f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "5067"
                        },
                        new
                        {
                            Id = new Guid("67dfbf5d-1850-42ae-a0f4-661d32f15e52"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4576"
                        },
                        new
                        {
                            Id = new Guid("7b80f7b3-ca2b-4826-945b-2651efbd18ba"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4011"
                        },
                        new
                        {
                            Id = new Guid("78607f37-648f-4f44-9996-33ad12a714fa"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509000"
                        },
                        new
                        {
                            Id = new Guid("8b591cfa-258a-4a7d-b619-ee5e9ba36340"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650905"
                        },
                        new
                        {
                            Id = new Guid("7947ba52-2f17-41ad-937b-db6d9f728c6a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650494"
                        },
                        new
                        {
                            Id = new Guid("888f3cca-091b-4f4b-b375-6967c9e14ff8"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650485"
                        },
                        new
                        {
                            Id = new Guid("fc54a4f1-6a54-4017-8a49-84349154e923"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509091"
                        },
                        new
                        {
                            Id = new Guid("b2f5de9e-c1c1-4e0d-9379-c1f24ef8e317"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650491"
                        },
                        new
                        {
                            Id = new Guid("939e53b9-86ba-469f-ad97-17c32835e9d9"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "65090"
                        },
                        new
                        {
                            Id = new Guid("a737a5ec-d9ab-4c82-a211-aac229572c7e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650487"
                        },
                        new
                        {
                            Id = new Guid("ecbe1d3f-9f8c-48f5-a658-3d9d5d7f91d2"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "506726"
                        },
                        new
                        {
                            Id = new Guid("7662decc-e708-4b09-9de7-df03d12de745"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "409835"
                        },
                        new
                        {
                            Id = new Guid("f8100aea-d8c9-4335-85fc-e9870fb5cd2e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("a7840efe-7668-40a9-bf65-3e4f43ebc80b"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650921"
                        },
                        new
                        {
                            Id = new Guid("cd449ce4-ec99-461e-878b-b7b284c6784a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650912"
                        },
                        new
                        {
                            Id = new Guid("8703460a-828d-4928-9a69-4cb97acad932"),
                            Brand = "HIPERCARD",
                            Order = 0,
                            Prefix = "506282"
                        },
                        new
                        {
                            Id = new Guid("7989c0be-2c68-455d-96ca-a2b10f3bc6f9"),
                            Brand = "HIPERCARD",
                            Order = 60,
                            Prefix = "38"
                        },
                        new
                        {
                            Id = new Guid("03021c6a-ab74-4194-9008-ccc40b3454b2"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "606282"
                        },
                        new
                        {
                            Id = new Guid("ac7bf604-5bd2-4dd0-8099-c15a88a7cbd0"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "3841"
                        },
                        new
                        {
                            Id = new Guid("fa55f0bb-898d-4ed4-aed7-4c345098d12f"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "2131"
                        },
                        new
                        {
                            Id = new Guid("068c0d0c-ff50-47bd-86ee-54ab4160b9fd"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "1800"
                        },
                        new
                        {
                            Id = new Guid("c17945d1-dfac-4528-92d3-58ba7b8673a9"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "546479"
                        },
                        new
                        {
                            Id = new Guid("ae29ebf9-69c0-4b66-abdf-2e48690e4a75"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("c31a0eb8-6ff4-4aef-a0c8-2e04fe66fa2c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "589916"
                        },
                        new
                        {
                            Id = new Guid("4cb807b0-2380-4d25-8b56-db1eff7b6d86"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "585988"
                        },
                        new
                        {
                            Id = new Guid("e9aec32b-6185-4b1d-92f7-872a6584e30b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("ca5a23a0-ee54-4efc-ac1b-c13ce30f3af5"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "439133"
                        },
                        new
                        {
                            Id = new Guid("7f8612d9-1ec0-452e-a3d7-02461952ec29"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "55909"
                        },
                        new
                        {
                            Id = new Guid("f19990fa-38ac-4b17-80f8-6cd7ad9f714b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "53508"
                        },
                        new
                        {
                            Id = new Guid("73aa02f6-7f3a-41fc-9aa1-f878a47ecb53"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "320132"
                        },
                        new
                        {
                            Id = new Guid("b58cae42-3b1a-4b33-adc0-0605ca3c53be"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "126820"
                        },
                        new
                        {
                            Id = new Guid("f77d1687-99cd-448e-ae7b-38536c2b87a7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576292"
                        },
                        new
                        {
                            Id = new Guid("741f140c-5beb-428c-b502-643d754fe23a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5453"
                        },
                        new
                        {
                            Id = new Guid("4f55c6ab-649e-44b8-82a3-48063bb66211"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5379"
                        },
                        new
                        {
                            Id = new Guid("0d91f868-a9af-4b67-a4dd-4309f217da9a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "537993"
                        },
                        new
                        {
                            Id = new Guid("f49ba514-def7-4a62-a362-1d4aaad4b23a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "639350"
                        },
                        new
                        {
                            Id = new Guid("94c0a1c9-d3e7-47d9-91bf-365479d4f8f9"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "830050"
                        },
                        new
                        {
                            Id = new Guid("f70886d7-dcba-451a-8bea-57a215a8865e"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "517349"
                        },
                        new
                        {
                            Id = new Guid("87ab02f5-b316-48ac-95c5-5b771ba96f88"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560033"
                        },
                        new
                        {
                            Id = new Guid("21bc57ee-6b18-45a3-ba13-db6e985dbd9a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505381"
                        },
                        new
                        {
                            Id = new Guid("519f03fa-651b-4558-8fed-5030bea1d6ab"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "595922"
                        },
                        new
                        {
                            Id = new Guid("08b48b51-5431-4a5c-9b4b-c18590e2505e"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "007807"
                        },
                        new
                        {
                            Id = new Guid("bbc8335f-21ac-4f3b-9895-195dc8039172"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509257"
                        },
                        new
                        {
                            Id = new Guid("f0c45cd5-388c-44b5-8287-1de96c580545"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502309"
                        },
                        new
                        {
                            Id = new Guid("5eee4e2e-fa5a-4eaf-a660-66ec80483dc7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "212743"
                        },
                        new
                        {
                            Id = new Guid("8310cfff-2ce9-488f-9472-0935b2b2c23c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505316"
                        },
                        new
                        {
                            Id = new Guid("7a24a105-c838-42c3-a76c-74f52731b233"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "720358"
                        },
                        new
                        {
                            Id = new Guid("6b272f7e-2d41-48a0-8b76-c51ec97f1f89"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502299"
                        },
                        new
                        {
                            Id = new Guid("a7bf25c7-75c7-4e4f-9cfe-f18838d5ff13"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "330239"
                        },
                        new
                        {
                            Id = new Guid("c87079de-67b1-4461-8119-87a2f858b61d"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "640245"
                        },
                        new
                        {
                            Id = new Guid("443bd561-1f52-4d1b-8dc2-789fda1f7659"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "003006"
                        },
                        new
                        {
                            Id = new Guid("5feefe95-f62c-41e4-bb78-82c75857ce2c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "615292"
                        },
                        new
                        {
                            Id = new Guid("bf681118-f178-4c8e-86c4-3b1deeb45111"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "574080"
                        },
                        new
                        {
                            Id = new Guid("3f02e54d-fd91-4968-b7f0-56e71698a746"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "608710"
                        },
                        new
                        {
                            Id = new Guid("e1c5586d-fced-4bd0-b9fd-3546b1e223a4"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "507641"
                        },
                        new
                        {
                            Id = new Guid("68d08bf5-9edc-4cfc-be6c-8b3116175f3d"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "316811"
                        },
                        new
                        {
                            Id = new Guid("e358c814-280d-45eb-872c-920cd492b095"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "569970"
                        },
                        new
                        {
                            Id = new Guid("e6932ba8-8947-4555-a1d3-e93b37bc49a3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960397"
                        },
                        new
                        {
                            Id = new Guid("cbd8e34e-7a1a-49eb-bb70-daea623fcc85"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "220209"
                        },
                        new
                        {
                            Id = new Guid("ad230cbe-9f7e-46e6-9b30-bcd0ce41e10b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "637095"
                        },
                        new
                        {
                            Id = new Guid("b8694624-7a37-4a1f-a021-39572403cdef"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576096"
                        },
                        new
                        {
                            Id = new Guid("86507397-c2fe-4e92-a44e-5b2ee5e1a41b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "596497"
                        },
                        new
                        {
                            Id = new Guid("5da1f97b-fb75-4c61-b535-a3cc73bc0633"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "570209"
                        },
                        new
                        {
                            Id = new Guid("ab9ca0f5-30a2-4db5-8526-6bf2cd678cee"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "044027"
                        },
                        new
                        {
                            Id = new Guid("a684588c-fd6b-4ce1-82a3-f1f9276976da"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960379"
                        },
                        new
                        {
                            Id = new Guid("e83043b6-560f-4746-a376-2536571017a7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "988996"
                        },
                        new
                        {
                            Id = new Guid("61c93e03-1fa7-44c1-a44b-159d6834e77d"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "608783"
                        },
                        new
                        {
                            Id = new Guid("d7198f2e-3210-480d-9bfb-3470bafc0f25"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "750209"
                        },
                        new
                        {
                            Id = new Guid("02ae6e45-adc6-484a-968c-efcc817cf14b"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "515894"
                        },
                        new
                        {
                            Id = new Guid("69fa4e15-c7e6-4ce9-9862-407e8ef876d1"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2221"
                        },
                        new
                        {
                            Id = new Guid("6c060d1d-8c2f-45bd-83e5-b8765cea39ee"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2222"
                        },
                        new
                        {
                            Id = new Guid("7d7bda98-6e41-4463-9725-59b587e741da"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2223"
                        },
                        new
                        {
                            Id = new Guid("3984dea5-ba1e-461c-af58-dd5ff7069845"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2224"
                        },
                        new
                        {
                            Id = new Guid("986c650d-77b2-4ebd-ba3a-05e19e28ba87"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2225"
                        },
                        new
                        {
                            Id = new Guid("e28503e3-ff7e-47b7-aba8-6d4654ccf5fb"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2226"
                        },
                        new
                        {
                            Id = new Guid("e23f8298-2a50-46f8-a78d-6a362aff5a49"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2227"
                        },
                        new
                        {
                            Id = new Guid("48591305-20b7-4e23-b4f8-661c797d8a5a"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2228"
                        },
                        new
                        {
                            Id = new Guid("e1c13d5e-0221-4b5d-9faa-378bed549cf3"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2229"
                        },
                        new
                        {
                            Id = new Guid("88395a41-5e25-4663-bd77-a4cbaa2989b0"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "223"
                        },
                        new
                        {
                            Id = new Guid("fec41d70-aa8e-40f5-9b76-e2df4b02ccb9"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "224"
                        },
                        new
                        {
                            Id = new Guid("9920629d-d69b-47c4-8261-a13885ec06f6"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "225"
                        },
                        new
                        {
                            Id = new Guid("7d069fcf-1e15-4757-bb62-fc8ace46c0c4"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "226"
                        },
                        new
                        {
                            Id = new Guid("69cfdbd2-7a03-44f3-9b22-9ab9c302cc37"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "227"
                        },
                        new
                        {
                            Id = new Guid("84aaa2a3-d5bf-462a-8554-6e13588f291a"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "228"
                        },
                        new
                        {
                            Id = new Guid("ee4a29a6-ec2a-40ff-839a-924bf0aa6147"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "229"
                        },
                        new
                        {
                            Id = new Guid("c1196f95-2f9b-4e2d-8c68-6702e3393a89"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "23"
                        },
                        new
                        {
                            Id = new Guid("56ba5f1a-ced6-4179-8e1d-e0310dde74b3"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "24"
                        },
                        new
                        {
                            Id = new Guid("6136fec1-3021-40d2-8f70-37e7c9c5384b"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "25"
                        },
                        new
                        {
                            Id = new Guid("6b1b71d5-23e5-4e60-b740-25b3fc7569e4"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "26"
                        },
                        new
                        {
                            Id = new Guid("940e0f85-d19b-43cb-982c-1f1e15deb620"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "271"
                        },
                        new
                        {
                            Id = new Guid("1866854f-75e4-48f7-afa8-8f5ebbad4c15"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2720"
                        },
                        new
                        {
                            Id = new Guid("51832641-df38-4420-85d8-4a4d8319342c"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "51"
                        },
                        new
                        {
                            Id = new Guid("07e5a965-a474-4686-974b-47c90b528c06"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "52"
                        },
                        new
                        {
                            Id = new Guid("45a82d8f-f94e-4022-b8ea-8e333d10fa28"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "53"
                        },
                        new
                        {
                            Id = new Guid("2a91a797-706f-4aa0-b956-5105e9ec7e94"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "54"
                        },
                        new
                        {
                            Id = new Guid("c84779fa-e8ee-4508-8e80-775b0727716d"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "55"
                        },
                        new
                        {
                            Id = new Guid("b86a08ba-7ef8-42af-8039-47e862936d91"),
                            Brand = "NARANJA E NEVADA",
                            Order = 100,
                            Prefix = "589562"
                        },
                        new
                        {
                            Id = new Guid("2f268b01-22cc-4333-8b14-ca3676d32a18"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "627892"
                        },
                        new
                        {
                            Id = new Guid("67b97e41-3a32-47c7-88f5-b08b28ca6442"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "121772"
                        },
                        new
                        {
                            Id = new Guid("43ed3784-00b3-4632-9290-09e59ce9c7e3"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "40064"
                        },
                        new
                        {
                            Id = new Guid("0f95b35d-b088-43f1-afdc-f1330ef094ff"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "444125"
                        },
                        new
                        {
                            Id = new Guid("d4863a73-eafa-4e91-9e31-a890cc11e225"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "798431"
                        },
                        new
                        {
                            Id = new Guid("f6366254-277e-4e2a-8f2d-00ff4b964b83"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "48546"
                        },
                        new
                        {
                            Id = new Guid("69a4bca6-db70-4086-86f4-1daeb0cc3bab"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "988442"
                        },
                        new
                        {
                            Id = new Guid("6415ce04-2849-4df0-9734-27dcbc562c49"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("28ab96b0-c938-4dfc-a2db-a1ec475bcf1a"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("3303cee1-40fb-449f-8605-90e092b28d24"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("cf4c6b6d-810f-42a2-83f9-501716ac859c"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "984428"
                        },
                        new
                        {
                            Id = new Guid("9c85bcf1-862a-4f10-bd8a-67655d47b148"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "636355"
                        },
                        new
                        {
                            Id = new Guid("52b1ba66-7e36-4820-9cd2-b009685ab521"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "027728"
                        },
                        new
                        {
                            Id = new Guid("36894d44-4f2d-4140-8374-bd81bec5b943"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "107915"
                        },
                        new
                        {
                            Id = new Guid("2454f6c5-e0f5-46e5-a704-79ce888dda83"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "210790"
                        },
                        new
                        {
                            Id = new Guid("54b77a7f-4d86-44d3-b172-ce460b7ce84c"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "854644"
                        },
                        new
                        {
                            Id = new Guid("84b1df64-5352-4fdf-9817-492ce3da2684"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "033994"
                        },
                        new
                        {
                            Id = new Guid("f898b6b1-7cdd-4f8c-8cfc-35005326c523"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "985966"
                        },
                        new
                        {
                            Id = new Guid("76354b51-5520-4415-bab9-03073028ddbe"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "960421"
                        },
                        new
                        {
                            Id = new Guid("11b3dedf-f205-4f08-a247-1888ed5ddf7b"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "186307"
                        },
                        new
                        {
                            Id = new Guid("d38e16f5-ca2e-42df-9c39-3ac77bf79f8d"),
                            Brand = "VISA",
                            Order = 5,
                            Prefix = "4984"
                        },
                        new
                        {
                            Id = new Guid("f8418814-2f4b-466b-9a11-876be7daf054"),
                            Brand = "VISA",
                            Order = 110,
                            Prefix = "4"
                        });
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BraspagProvider")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("FeevCheckout.Models.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankAgency")
                        .HasColumnType("text");

                    b.Property<string>("BankNumber")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CheckingAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("ExtraData")
                        .HasColumnType("jsonb");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.Property<JsonDocument>("Response")
                        .HasColumnType("jsonb");

                    b.Property<PaymentAttemptStatus>("Status")
                        .HasColumnType("payment_attempt_status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("TransactionId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SuccessfulPaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("SuccessfulPaymentAttemptId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany("Products")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.PaymentAttempt", "SuccessfulPaymentAttempt")
                        .WithMany()
                        .HasForeignKey("SuccessfulPaymentAttemptId");

                    b.OwnsOne("FeevCheckout.Models.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Document")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerDocument");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerName");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("FeevCheckout.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("CustomerTransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressCity");

                                    b2.Property<string>("Complement")
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressComplement");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressDistrict");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressNumber");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressState");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressStreet");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressZipCode");

                                    b2.HasKey("CustomerTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerTransactionId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("SuccessfulPaymentAttempt");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
