// <auto-generated />
using System;
using System.Text.Json;
using FeevCheckout.Data;
using FeevCheckout.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeevCheckout.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126141719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_attempt_status", new[] { "pending", "created", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "feev_pix", "feev_boleto", "braspag_cartao" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeevCheckout.Models.CardBrandPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardBrandPatterns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05b1ce54-7f86-48f5-872e-c6ae7ba735d7"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "34"
                        },
                        new
                        {
                            Id = new Guid("23bb3055-647d-4bc3-b838-98a2d46e2119"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("45394277-6bfd-41ec-9e30-9027e083bfde"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("20554144-3fdb-47a1-b373-87218211e503"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "37"
                        },
                        new
                        {
                            Id = new Guid("ddcaba72-bc88-4327-ae2c-7d796a82ddee"),
                            Brand = "CABAL",
                            Order = 60,
                            Prefix = "6042"
                        },
                        new
                        {
                            Id = new Guid("c11cca32-ed79-44d8-b42e-11cf9873e42a"),
                            Brand = "DINERS",
                            Order = 0,
                            Prefix = "605919"
                        },
                        new
                        {
                            Id = new Guid("13f031e0-e546-46fe-8474-865a009a832c"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "300"
                        },
                        new
                        {
                            Id = new Guid("14d5c5ec-4aa8-46ff-a797-f27b98c93014"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "301"
                        },
                        new
                        {
                            Id = new Guid("423f9d1c-1874-49b4-8d4e-0f941f7c7505"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "302"
                        },
                        new
                        {
                            Id = new Guid("b87c558c-c996-4050-81a0-a8570910048c"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "303"
                        },
                        new
                        {
                            Id = new Guid("c37a1ba3-aeb5-4cce-86f2-dc00ae664678"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "304"
                        },
                        new
                        {
                            Id = new Guid("a04e48e4-3fa4-4964-85e6-bc797307c615"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "305"
                        },
                        new
                        {
                            Id = new Guid("b9bd0699-7af0-48d8-8f14-915be884ae13"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("bfd09fec-9f46-47fa-95a4-c00f0d63d3d4"),
                            Brand = "DISCOVER",
                            Order = 1,
                            Prefix = "306262"
                        },
                        new
                        {
                            Id = new Guid("aabad584-d0c9-42ee-881b-7e663819986b"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6011"
                        },
                        new
                        {
                            Id = new Guid("d3a67c1c-ad20-47e4-9dfe-5f0908c364af"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "65"
                        },
                        new
                        {
                            Id = new Guid("fa8dc73a-af9f-4a73-bc1e-42e387e901e1"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "644"
                        },
                        new
                        {
                            Id = new Guid("ca16b818-3920-418b-aa9c-116efef91682"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "645"
                        },
                        new
                        {
                            Id = new Guid("40c2ce8b-6856-4809-b27b-4fd9817b34da"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "646"
                        },
                        new
                        {
                            Id = new Guid("c95dab81-a5bf-471a-97af-0fd7f670fbab"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "647"
                        },
                        new
                        {
                            Id = new Guid("2cf4364f-e126-4f21-a891-f66445809dba"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "648"
                        },
                        new
                        {
                            Id = new Guid("357452f7-5187-4037-a2f3-68726506fbf6"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "649"
                        },
                        new
                        {
                            Id = new Guid("9af7c82d-2d36-47b2-8933-a8620e427b0c"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622126"
                        },
                        new
                        {
                            Id = new Guid("6b7c2cb6-4ed9-4720-9161-9cbe0be9b07f"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622127"
                        },
                        new
                        {
                            Id = new Guid("896a25f1-7d39-446e-8a9f-548160a2adb1"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622128"
                        },
                        new
                        {
                            Id = new Guid("2a8d4bdb-a301-4d50-91f4-9a03d8a28cd7"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622129"
                        },
                        new
                        {
                            Id = new Guid("d5086915-b137-4acf-81d7-264d65d6f1cb"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62213"
                        },
                        new
                        {
                            Id = new Guid("140002b3-939a-4e14-a393-e0f2f0b95d98"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62214"
                        },
                        new
                        {
                            Id = new Guid("426aa0fe-1a19-4ce7-9049-28ab78121ee3"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62215"
                        },
                        new
                        {
                            Id = new Guid("f378f748-162b-4f50-83e7-19d7ffef8742"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62216"
                        },
                        new
                        {
                            Id = new Guid("4befd7bb-618f-4b65-956e-5b6833411015"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62217"
                        },
                        new
                        {
                            Id = new Guid("5a1ff8c2-2ace-40f8-9a7d-026008c4db5d"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62218"
                        },
                        new
                        {
                            Id = new Guid("8cfab46d-5200-4d2a-9d10-5a3c1c493eff"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62219"
                        },
                        new
                        {
                            Id = new Guid("f0f21d1b-0dd8-470b-9989-49d4ad351640"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6222"
                        },
                        new
                        {
                            Id = new Guid("003ca013-ebc2-4cae-b9bb-8a36f2a62b5d"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6223"
                        },
                        new
                        {
                            Id = new Guid("86f23be4-eb81-49dc-b4f7-90338ad348bf"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6224"
                        },
                        new
                        {
                            Id = new Guid("42e3cc17-8d0f-44e8-a966-2a3ffc049a23"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6225"
                        },
                        new
                        {
                            Id = new Guid("ef69207b-8e29-4732-b169-705138eeb9ec"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6226"
                        },
                        new
                        {
                            Id = new Guid("58f3277e-2b4e-41d6-a2c6-70ba30680c8e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6227"
                        },
                        new
                        {
                            Id = new Guid("207794f8-ed91-4007-814c-07e088613ff4"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6228"
                        },
                        new
                        {
                            Id = new Guid("6e104ced-1dcb-4b88-9daf-89a103d5b994"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62290"
                        },
                        new
                        {
                            Id = new Guid("f6570cca-3017-4daf-9624-e7f3add45aec"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62291"
                        },
                        new
                        {
                            Id = new Guid("7e4af5f4-a029-447e-9fcb-90befde26747"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622920"
                        },
                        new
                        {
                            Id = new Guid("ee4aa599-02f3-4465-bc88-207538f6d27e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622921"
                        },
                        new
                        {
                            Id = new Guid("f8fa036f-3ee6-4325-96b8-a7f639be3134"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622922"
                        },
                        new
                        {
                            Id = new Guid("a53b134e-d42d-4142-9921-2034417563b9"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622923"
                        },
                        new
                        {
                            Id = new Guid("b9edfac7-ab54-4b4f-88ff-f753e956a03b"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622924"
                        },
                        new
                        {
                            Id = new Guid("2784b6e5-734c-4490-9287-2b1ab6a42ad4"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622925"
                        },
                        new
                        {
                            Id = new Guid("8c19b8b9-896e-4f8c-872a-72d381f2c9c0"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "627780"
                        },
                        new
                        {
                            Id = new Guid("6167a90a-fd65-4279-937a-cbe6a1766f43"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "67410"
                        },
                        new
                        {
                            Id = new Guid("cf2c69ac-c01e-445a-8455-ac6dbd84bf4f"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "111111"
                        },
                        new
                        {
                            Id = new Guid("7218e237-a417-4d28-8d39-f0425b00d001"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "506874"
                        },
                        new
                        {
                            Id = new Guid("d0dbd78b-3c16-498c-af71-b532c220a4e3"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "640485"
                        },
                        new
                        {
                            Id = new Guid("74b58e28-2558-49db-bfa2-5e120a91f5cd"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509093"
                        },
                        new
                        {
                            Id = new Guid("7a1edf38-4cfb-482c-b10e-31100dc3967f"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650042"
                        },
                        new
                        {
                            Id = new Guid("0550c691-6bbb-4c0f-9eac-7372e1ad6d23"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("cfeea6d1-8f95-4751-ba5c-8d8ff9a09609"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("e3d29cc4-6253-4e29-8281-da32f81e1d8c"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509005"
                        },
                        new
                        {
                            Id = new Guid("14d8a98e-9eee-46d9-b1ae-c73fdfc56469"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650920"
                        },
                        new
                        {
                            Id = new Guid("7603940e-9c51-45cd-9a29-4428e9e9db09"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "699988"
                        },
                        new
                        {
                            Id = new Guid("47ff6a78-5958-4830-88a7-ad74f0dda9df"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "508757"
                        },
                        new
                        {
                            Id = new Guid("4f917698-6f82-4dae-bec0-2b01668baeda"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "680405"
                        },
                        new
                        {
                            Id = new Guid("c8b91ff0-d28d-43cb-961c-87d1f79970a0"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509423"
                        },
                        new
                        {
                            Id = new Guid("1f3b8ff6-b8dc-4731-ad0c-7bac237ccdd3"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6538"
                        },
                        new
                        {
                            Id = new Guid("494e8a2f-e9d9-4bfd-9374-aefa53548401"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509156"
                        },
                        new
                        {
                            Id = new Guid("23c30aeb-719f-41c5-94c2-0d0ea7c91118"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509284"
                        },
                        new
                        {
                            Id = new Guid("be18e58a-648a-47c0-a47d-3c252ea6b56d"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "502577"
                        },
                        new
                        {
                            Id = new Guid("a9dd2458-4140-4a0c-98d7-e98980316a7d"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509004"
                        },
                        new
                        {
                            Id = new Guid("1a4bdc97-6389-4560-a145-64e133e78642"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509294"
                        },
                        new
                        {
                            Id = new Guid("898e9f08-8dbb-4b5e-a9f7-9333123f9733"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509730"
                        },
                        new
                        {
                            Id = new Guid("204dbfc7-a5bf-453c-90a1-82ebb5be8f36"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509010"
                        },
                        new
                        {
                            Id = new Guid("c790b10b-0b6f-466b-a586-889ea5f4381c"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6509"
                        },
                        new
                        {
                            Id = new Guid("7083e8bd-dc7f-4db2-80fb-a690617a1aac"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "6507"
                        },
                        new
                        {
                            Id = new Guid("392bb78d-e5eb-4853-90ec-c12ae199c3db"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "650914"
                        },
                        new
                        {
                            Id = new Guid("1f5ed430-5e2a-453e-8b3c-1cfd120a9217"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "509274"
                        },
                        new
                        {
                            Id = new Guid("bb4178f3-5243-4d2e-9695-096f45ac2259"),
                            Brand = "ELO",
                            Order = 4,
                            Prefix = "506741"
                        },
                        new
                        {
                            Id = new Guid("7a5ce568-cb4c-4975-ae5d-8eb49489b3f7"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6505"
                        },
                        new
                        {
                            Id = new Guid("1eefb3ff-b14b-4729-8f2d-7a69f7a40d80"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6280"
                        },
                        new
                        {
                            Id = new Guid("39c58b4c-4194-4e43-9807-bb2045b1c552"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6504"
                        },
                        new
                        {
                            Id = new Guid("c3a0f9c7-7173-4963-8d16-05247462fa89"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6550"
                        },
                        new
                        {
                            Id = new Guid("ba1de02c-3a8a-4294-9164-2ac70fe406ea"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "509023"
                        },
                        new
                        {
                            Id = new Guid("0da4373c-2933-4980-96a2-4c9f08169aa1"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6516"
                        },
                        new
                        {
                            Id = new Guid("2e2944ec-61a9-4a59-ba3c-fcb34ccb2627"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650507"
                        },
                        new
                        {
                            Id = new Guid("2131f038-e60f-4eb1-a1fe-533c6cbc3bfb"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "636368"
                        },
                        new
                        {
                            Id = new Guid("0e86b520-54f9-4d44-8b0f-2309416551f3"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "438935"
                        },
                        new
                        {
                            Id = new Guid("8bbb1da9-76fa-446d-83c6-238912cc3b98"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "504175"
                        },
                        new
                        {
                            Id = new Guid("42baf655-d570-435d-b789-4cd57d7c4981"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "451416"
                        },
                        new
                        {
                            Id = new Guid("c0ba026e-7d79-4943-ae65-edf14f5a72f7"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("b3772fad-3bd7-4891-a118-9ebf270a1d6b"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509067"
                        },
                        new
                        {
                            Id = new Guid("5c3d0094-37c0-476a-91a5-8d53ace96adb"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509049"
                        },
                        new
                        {
                            Id = new Guid("ed736c5e-ff2d-4d13-85ce-4675a966c49e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509069"
                        },
                        new
                        {
                            Id = new Guid("780d7b75-9d66-4cf0-ae4a-03a79fcb01aa"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509050"
                        },
                        new
                        {
                            Id = new Guid("3905d34f-4f18-45de-a214-85744d446cf3"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509074"
                        },
                        new
                        {
                            Id = new Guid("5ffc17d1-e0aa-4753-be75-4cf098220a85"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50906"
                        },
                        new
                        {
                            Id = new Guid("4c2b3fd1-7631-4076-9ede-330372fbafb7"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("02368803-b488-46d3-8a05-8bc17394df4e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509045"
                        },
                        new
                        {
                            Id = new Guid("83dc1d02-efc9-476f-91fe-41554f21ca74"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509051"
                        },
                        new
                        {
                            Id = new Guid("b91f93d7-92b5-4241-86e1-e4344782c8bc"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509046"
                        },
                        new
                        {
                            Id = new Guid("fe26c2f6-f87f-40a4-bc46-f0ed73a90e9f"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509066"
                        },
                        new
                        {
                            Id = new Guid("0597e697-a01c-478a-bc42-365c4135cfe8"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("965b7f59-f2ba-4eba-bf22-a1a07714cd88"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509042"
                        },
                        new
                        {
                            Id = new Guid("eefc0690-c626-4986-99dd-1f6dbfc4bac1"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509052"
                        },
                        new
                        {
                            Id = new Guid("ae849b51-ea12-4d43-86a0-8c6d9119ed7e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509043"
                        },
                        new
                        {
                            Id = new Guid("42b59229-509f-4a24-aed1-983583429b6d"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509064"
                        },
                        new
                        {
                            Id = new Guid("c97bafe1-1412-42dc-961b-564ba4a92ce4"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("1eb5c78f-a23b-4f3c-b495-90ebb49579c5"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "36297"
                        },
                        new
                        {
                            Id = new Guid("889d3111-6180-48db-ba5b-835e7f960db6"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "5067"
                        },
                        new
                        {
                            Id = new Guid("3190514e-4e2f-4f2c-97b6-fb064bab71e7"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4576"
                        },
                        new
                        {
                            Id = new Guid("80729eec-ea75-4613-a720-4f0e773dbad2"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4011"
                        },
                        new
                        {
                            Id = new Guid("20bb2330-e2fe-4938-8563-1d695ba18fec"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509000"
                        },
                        new
                        {
                            Id = new Guid("ae290d4c-bd22-4c3c-9f59-98f402c24cd8"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650905"
                        },
                        new
                        {
                            Id = new Guid("5cd6bec0-c70f-44c1-92b4-70e8eb6a862c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650494"
                        },
                        new
                        {
                            Id = new Guid("3b612e2f-0b55-49c7-bb4e-1745dcb1d52a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650485"
                        },
                        new
                        {
                            Id = new Guid("620c8e49-e384-4fa4-8c4b-77616844a0cb"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509091"
                        },
                        new
                        {
                            Id = new Guid("85904af7-a34f-4f11-a38d-0a7c5286f1b1"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650491"
                        },
                        new
                        {
                            Id = new Guid("5ff0e16e-fbd2-492f-9857-d4d1ea1068af"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "65090"
                        },
                        new
                        {
                            Id = new Guid("93e7517c-4a78-4c41-b37c-44f2e119eaa9"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650487"
                        },
                        new
                        {
                            Id = new Guid("0827d174-1cb2-4be4-a1c7-ab21ee846115"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "409835"
                        },
                        new
                        {
                            Id = new Guid("193bd82e-3cb3-45d9-9256-f2a51e425699"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("8c84b351-aaf5-445d-9c21-c2264485b611"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650921"
                        },
                        new
                        {
                            Id = new Guid("4f5b783e-e628-4832-8f6d-a2494631c0ea"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650912"
                        },
                        new
                        {
                            Id = new Guid("7becaa1e-4c35-453d-b142-2df2a6802002"),
                            Brand = "HIPERCARD",
                            Order = 0,
                            Prefix = "506282"
                        },
                        new
                        {
                            Id = new Guid("da73bb3a-939e-4db3-8727-78e0465ffc4a"),
                            Brand = "HIPERCARD",
                            Order = 60,
                            Prefix = "38"
                        },
                        new
                        {
                            Id = new Guid("be993bbb-927d-4fe6-9e47-6969b920286b"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "606282"
                        },
                        new
                        {
                            Id = new Guid("91946c7e-123c-49d1-874b-e390b3396a5c"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "3841"
                        },
                        new
                        {
                            Id = new Guid("d2b5be9e-ac4c-4218-8ba5-73a4ccbd14ec"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "2131"
                        },
                        new
                        {
                            Id = new Guid("f868c53f-55dd-416b-91ee-ff0640f3e2f6"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "1800"
                        },
                        new
                        {
                            Id = new Guid("e0e0d7e8-9047-4ccf-b293-704fd67a2288"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("6497a227-ec37-44d3-a77a-bcb2cc80f332"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "546479"
                        },
                        new
                        {
                            Id = new Guid("20e7fcff-de40-4abd-88ce-bef52b9b1c8a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("3a82b5c4-2153-4e87-bd08-4fa85bfdca9f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "589916"
                        },
                        new
                        {
                            Id = new Guid("4c6cb400-e78a-48b1-b056-9d21486d9478"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "585988"
                        },
                        new
                        {
                            Id = new Guid("39c25b53-3bb8-4fae-bba5-78e4344b7985"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("d3c8c7e1-14e2-4a6b-aad8-4532e16e5dab"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "439133"
                        },
                        new
                        {
                            Id = new Guid("ad7ecacd-10f4-425b-87bf-982b44d5e06f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "55909"
                        },
                        new
                        {
                            Id = new Guid("84f534bd-ab60-4117-8983-4f68cf4d2d28"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "53508"
                        },
                        new
                        {
                            Id = new Guid("dbabbfe6-3782-409a-a08b-5d187fd67642"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "320132"
                        },
                        new
                        {
                            Id = new Guid("5f2cdf81-7c20-4915-9fc6-940ae81122bf"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "126820"
                        },
                        new
                        {
                            Id = new Guid("0f80fd08-8aa0-4b8d-b8f6-86805829e0c3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576292"
                        },
                        new
                        {
                            Id = new Guid("a4ff758d-2979-4cda-91c4-bb1b3b0c97b3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5453"
                        },
                        new
                        {
                            Id = new Guid("0372d39d-ff94-464e-821a-f0265cfed04b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5379"
                        },
                        new
                        {
                            Id = new Guid("6d0b34de-32b6-411f-97c9-5897f208c451"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "537993"
                        },
                        new
                        {
                            Id = new Guid("db597607-4b52-4fc8-8be7-9eabcb0fdb4a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "639350"
                        },
                        new
                        {
                            Id = new Guid("2e9c2a21-33af-4fe9-821f-52358f5027b6"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "830050"
                        },
                        new
                        {
                            Id = new Guid("6bddf73a-c0ff-4dfe-93a0-6e743b2f96a0"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "517349"
                        },
                        new
                        {
                            Id = new Guid("d205370b-7c51-479c-8380-04072fb0f30f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("b6c38a2b-d006-4fad-8090-c21a6ece57d9"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560033"
                        },
                        new
                        {
                            Id = new Guid("149f3dad-3f31-4a3d-beeb-027bbd93998f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505381"
                        },
                        new
                        {
                            Id = new Guid("d891674c-4039-4724-aaa2-682c10238bf3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("50baf0cd-e00e-4cdc-bd3d-ba09f98497a4"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "595922"
                        },
                        new
                        {
                            Id = new Guid("bd97ec5c-9e84-4722-84e6-19a2da4756d7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("58920d2c-44e7-48de-8d60-bcd591d70145"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "7807"
                        },
                        new
                        {
                            Id = new Guid("e1e5b16c-3742-4e1b-8828-80a98a7eef77"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509257"
                        },
                        new
                        {
                            Id = new Guid("6cd62b8d-21bf-4435-99b9-f26c611eab84"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502309"
                        },
                        new
                        {
                            Id = new Guid("245fb9ef-0be9-4fb9-8808-593045dc424a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "212743"
                        },
                        new
                        {
                            Id = new Guid("6c29bf88-0f06-4ce0-8a58-189979b96f1c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505316"
                        },
                        new
                        {
                            Id = new Guid("635c31f3-bbc8-4fc0-a1a9-16b568b327c3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "720358"
                        },
                        new
                        {
                            Id = new Guid("b96529a8-0fc1-4cb0-88f6-cba42b19a2c1"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502299"
                        },
                        new
                        {
                            Id = new Guid("5d2299c5-a37c-43dc-a932-63fcdb3d2298"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "330239"
                        },
                        new
                        {
                            Id = new Guid("f80c6c6d-e821-4dd7-a0f1-cc998f47bb3a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "640245"
                        },
                        new
                        {
                            Id = new Guid("112075dc-afda-42dc-82ff-34952749cd2d"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "3006"
                        },
                        new
                        {
                            Id = new Guid("0f532812-5a1c-4c0f-aafc-1d9623580336"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "615292"
                        },
                        new
                        {
                            Id = new Guid("da549a33-686a-4aa8-89b1-f08d3095a72c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "574080"
                        },
                        new
                        {
                            Id = new Guid("c4df1f22-e790-4948-a819-abeaa7693ebc"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "608710"
                        },
                        new
                        {
                            Id = new Guid("e0ae42d4-ec5d-4f2c-a082-574aa625b8e0"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "507641"
                        },
                        new
                        {
                            Id = new Guid("1998ec6e-986d-494e-a0ef-8c1f43d1e992"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "316811"
                        },
                        new
                        {
                            Id = new Guid("8226d599-c8b7-4bad-9c7a-8cb428f47a4f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "569970"
                        },
                        new
                        {
                            Id = new Guid("f7db8949-c05d-4b17-a2e7-7ed85b24b67c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960397"
                        },
                        new
                        {
                            Id = new Guid("b2932bde-922a-45fa-b73a-b97ce915a15d"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "220209"
                        },
                        new
                        {
                            Id = new Guid("431e24fb-a724-49b7-a0bf-f183015b6de4"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "637095"
                        },
                        new
                        {
                            Id = new Guid("50e71794-c759-4eb1-921c-2fae18d088cb"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576096"
                        },
                        new
                        {
                            Id = new Guid("1217e59d-8ba1-4f0a-844c-d93bcea0acc4"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "596497"
                        },
                        new
                        {
                            Id = new Guid("2f301774-4bb8-4a19-8205-311247e6484d"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "570209"
                        },
                        new
                        {
                            Id = new Guid("2ab53a7f-4b66-43a6-bebe-4c0d20097ab3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "44027"
                        },
                        new
                        {
                            Id = new Guid("81ee61f1-ecb5-4f1c-8388-3bfc7a0d560a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960379"
                        },
                        new
                        {
                            Id = new Guid("aaf21de7-a469-4328-a35d-9658d917cf89"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "608783"
                        },
                        new
                        {
                            Id = new Guid("b382fdd2-e26f-4aec-826f-089d45147836"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "750209"
                        },
                        new
                        {
                            Id = new Guid("2868f315-bb0e-404d-b43e-fd19679f9682"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "515894"
                        },
                        new
                        {
                            Id = new Guid("12512908-6dbd-4598-b932-355c0eb3a025"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2221"
                        },
                        new
                        {
                            Id = new Guid("7ee5c159-16d2-4cd8-bed6-b8422e56b655"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2222"
                        },
                        new
                        {
                            Id = new Guid("9e4bd89d-eba3-4a56-bab8-1ff80bc1e300"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2223"
                        },
                        new
                        {
                            Id = new Guid("074d352d-e808-4ec6-b4ce-91fcd5bc478d"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2224"
                        },
                        new
                        {
                            Id = new Guid("c54e18b5-73fa-4aae-962b-50225e2957f6"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2225"
                        },
                        new
                        {
                            Id = new Guid("140283ed-f263-4085-9ba7-de36ddeb73f4"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2226"
                        },
                        new
                        {
                            Id = new Guid("5353880a-8720-4369-a0be-19955332d311"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2227"
                        },
                        new
                        {
                            Id = new Guid("8a819351-27e3-4991-9fa7-b5e9381fdd13"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2228"
                        },
                        new
                        {
                            Id = new Guid("90c0f4f3-7387-4de7-9d92-922c73bb6bcd"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2229"
                        },
                        new
                        {
                            Id = new Guid("1c5de06c-faef-4e5e-adca-1f599fd9ba95"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "223"
                        },
                        new
                        {
                            Id = new Guid("615b54ee-0fa5-4a9d-83df-371386bd03bf"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "224"
                        },
                        new
                        {
                            Id = new Guid("82e0bb07-94a8-4671-9798-41c62fcde07c"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "225"
                        },
                        new
                        {
                            Id = new Guid("2ee19789-b5a0-46f8-a9c1-bb3264bcd5a1"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "226"
                        },
                        new
                        {
                            Id = new Guid("824c64db-22d4-40bd-8358-54024dc07f14"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "227"
                        },
                        new
                        {
                            Id = new Guid("da0d3bed-181a-4201-98cb-326ec5668e4e"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "228"
                        },
                        new
                        {
                            Id = new Guid("f623d679-b511-49f1-9341-8d94955b920b"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "229"
                        },
                        new
                        {
                            Id = new Guid("a2f1cd02-22e0-4840-bdd8-221413dd56d4"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "23"
                        },
                        new
                        {
                            Id = new Guid("951f5097-ceeb-4a11-9179-b12141e0fa50"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "24"
                        },
                        new
                        {
                            Id = new Guid("e672dfd9-ff77-416b-a21c-9fb688802a70"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "25"
                        },
                        new
                        {
                            Id = new Guid("3b2b4695-4f51-4a66-975c-4be5f9c742fe"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "26"
                        },
                        new
                        {
                            Id = new Guid("fcbf8323-69fd-4eca-97a6-eae5c3938e64"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "271"
                        },
                        new
                        {
                            Id = new Guid("ba5f0b56-4b59-4d63-a5f5-43e133e71156"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2720"
                        },
                        new
                        {
                            Id = new Guid("a1992f42-cc76-45a5-ac52-953b67156c9f"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "51"
                        },
                        new
                        {
                            Id = new Guid("1845dd8f-0bda-4c48-a464-dbe98ec54d18"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "52"
                        },
                        new
                        {
                            Id = new Guid("44073e7c-0920-4616-8c37-5707d2837c24"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "53"
                        },
                        new
                        {
                            Id = new Guid("7162b706-ed8b-4481-8feb-c997dd184238"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "54"
                        },
                        new
                        {
                            Id = new Guid("d69871e3-1697-4c7f-8424-5476351f781f"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "55"
                        },
                        new
                        {
                            Id = new Guid("bc8cfa6f-cfaf-48f1-8b06-4aa9a44e6eab"),
                            Brand = "NARANJA E NEVADA",
                            Order = 100,
                            Prefix = "589562"
                        },
                        new
                        {
                            Id = new Guid("b12920c0-8282-4691-9948-db61546c5ca2"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "627892"
                        },
                        new
                        {
                            Id = new Guid("80d44c56-7c25-42da-9fe2-9dfd81b18eb2"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("ad552afb-bd64-4c5d-9b3f-6f81eefc1ba7"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "121772"
                        },
                        new
                        {
                            Id = new Guid("8e8a1f88-d6f7-46a2-9ea6-6f6681df13b1"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "40064"
                        },
                        new
                        {
                            Id = new Guid("d3814d80-1b06-438d-b14e-97f3123a82bd"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "444125"
                        },
                        new
                        {
                            Id = new Guid("39d68950-193c-41fa-a6cb-cd98021d51ca"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "798431"
                        },
                        new
                        {
                            Id = new Guid("d3eec0c4-ad64-43c7-b752-ecb7460c8ad8"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "48546"
                        },
                        new
                        {
                            Id = new Guid("eadb7f44-8da5-41cd-b349-bb05c9c65a74"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "988442"
                        },
                        new
                        {
                            Id = new Guid("768dc1ca-1b4d-4f80-ac3b-a000482fef37"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("6dbafbd3-7214-4766-a31c-35a276123b86"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("45e6bb9c-04c5-4409-9352-b392e9148ee4"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("258f3368-0550-4c4c-bbe2-7bc5999a7eca"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "984428"
                        },
                        new
                        {
                            Id = new Guid("91055709-76f9-4ac8-b291-3b91af7a76a5"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "636355"
                        },
                        new
                        {
                            Id = new Guid("7b2bbd5a-fb11-46b4-b74f-5b5291eab350"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "27728"
                        },
                        new
                        {
                            Id = new Guid("dffddc29-0ffb-4b4d-8904-7826e9764855"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "107915"
                        },
                        new
                        {
                            Id = new Guid("e34700a3-d5ac-4d77-9973-8bc42762c4bf"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "210790"
                        },
                        new
                        {
                            Id = new Guid("42c7b9ce-7917-48b3-a18b-091f095d9cc3"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "854644"
                        },
                        new
                        {
                            Id = new Guid("68448fcb-c813-403b-a302-4ced63a34a82"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "33994"
                        },
                        new
                        {
                            Id = new Guid("e07e64cb-3102-4f96-bbec-46e53c5bb156"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "985966"
                        },
                        new
                        {
                            Id = new Guid("1c5c003c-7bb0-489a-8fbb-11f10a63559b"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "960421"
                        },
                        new
                        {
                            Id = new Guid("f97b52fe-4334-4c50-a65f-e82cf5254c32"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "186307"
                        },
                        new
                        {
                            Id = new Guid("5076f15a-f83c-4f4a-adcb-e3b7e5c0dc3d"),
                            Brand = "VISA",
                            Order = 5,
                            Prefix = "4984"
                        },
                        new
                        {
                            Id = new Guid("946120b1-2232-45de-9ad1-22f9cccc0c96"),
                            Brand = "VISA",
                            Order = 110,
                            Prefix = "4"
                        });
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BraspagProvider")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("FeevCheckout.Models.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankAgency")
                        .HasColumnType("text");

                    b.Property<string>("BankNumber")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CheckingAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("ExtraData")
                        .HasColumnType("jsonb");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.Property<JsonDocument>("Response")
                        .HasColumnType("jsonb");

                    b.Property<PaymentAttemptStatus>("Status")
                        .HasColumnType("payment_attempt_status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("TransactionId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SuccessfulPaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("SuccessfulPaymentAttemptId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany("Products")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.PaymentAttempt", "SuccessfulPaymentAttempt")
                        .WithMany()
                        .HasForeignKey("SuccessfulPaymentAttemptId");

                    b.OwnsOne("FeevCheckout.Models.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Document")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerDocument");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerName");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("FeevCheckout.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("CustomerTransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressCity");

                                    b2.Property<string>("Complement")
                                        .HasColumnType("text");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressUF");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressStreet");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressPostalCode");

                                    b2.HasKey("CustomerTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerTransactionId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("SuccessfulPaymentAttempt");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
