// <auto-generated />
using System;
using System.Text.Json;
using FeevCheckout.Data;
using FeevCheckout.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeevCheckout.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_attempt_status", new[] { "pending", "created", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "feev_pix", "feev_boleto", "braspag_cartao" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeevCheckout.Models.CardBrandPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardBrandPatterns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f4b766b-4283-4276-ace4-305b36f9f477"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "34"
                        },
                        new
                        {
                            Id = new Guid("501d8c70-019e-4e30-aa47-36a70f06a4ac"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("2dd401d8-4ee5-44e2-872c-2a9ca5f4bd7d"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("baef3ee4-5786-4be1-af86-5e296fd7adbe"),
                            Brand = "AMEX",
                            Order = 40,
                            Prefix = "37"
                        },
                        new
                        {
                            Id = new Guid("50f6ed36-2f03-422a-afdc-9b068db4f193"),
                            Brand = "CABAL",
                            Order = 60,
                            Prefix = "6042"
                        },
                        new
                        {
                            Id = new Guid("a5e0c5b1-1ead-40eb-a93b-61200aa43115"),
                            Brand = "DINERS",
                            Order = 0,
                            Prefix = "605919"
                        },
                        new
                        {
                            Id = new Guid("fb1dcd78-7d83-4493-805a-b5c9f66cec28"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "300"
                        },
                        new
                        {
                            Id = new Guid("41ed3b63-f623-4b24-913f-af8fb70b8352"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "301"
                        },
                        new
                        {
                            Id = new Guid("79ce0aec-fdc1-49d8-8894-a4cd11e077c8"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "302"
                        },
                        new
                        {
                            Id = new Guid("9c3c15eb-be3b-4e12-b6f5-ad576b56520d"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "303"
                        },
                        new
                        {
                            Id = new Guid("d51d94c5-dd4a-4ca8-ae0a-61193865aa7a"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "304"
                        },
                        new
                        {
                            Id = new Guid("19459571-d258-4b67-8963-5d605399dcc2"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "305"
                        },
                        new
                        {
                            Id = new Guid("40970807-f897-4ead-b9e7-ff75f806d4a4"),
                            Brand = "DINERS",
                            Order = 30,
                            Prefix = "36"
                        },
                        new
                        {
                            Id = new Guid("8200fe5a-0df3-4aac-a833-1469f3aa4333"),
                            Brand = "DISCOVER",
                            Order = 1,
                            Prefix = "306262"
                        },
                        new
                        {
                            Id = new Guid("ad509314-5aa6-42fd-983a-c2bc67f66d25"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6011"
                        },
                        new
                        {
                            Id = new Guid("72f7ce26-1b8a-4b54-8366-7acac5fa9798"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "65"
                        },
                        new
                        {
                            Id = new Guid("11eade65-4c39-4970-a763-dea6f383c77a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "644"
                        },
                        new
                        {
                            Id = new Guid("3e362513-32dc-45f8-8627-557960c8203f"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "645"
                        },
                        new
                        {
                            Id = new Guid("7f181468-040a-466f-89d7-0f12d2d15c17"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "646"
                        },
                        new
                        {
                            Id = new Guid("8b4c594c-8c0c-4d7a-bffd-06519797b1ec"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "647"
                        },
                        new
                        {
                            Id = new Guid("831bc4f9-d0c2-4071-9a37-fe623504002b"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "648"
                        },
                        new
                        {
                            Id = new Guid("708600f5-65ee-42fe-9fd8-cbe07b3b0489"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "649"
                        },
                        new
                        {
                            Id = new Guid("31758c60-2da2-465e-9bdf-1b4d6c611ce4"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622126"
                        },
                        new
                        {
                            Id = new Guid("44a95072-45b3-4739-8c6c-0d688806c971"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622127"
                        },
                        new
                        {
                            Id = new Guid("99d379f4-3a00-4aff-a1da-68327d36093b"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622128"
                        },
                        new
                        {
                            Id = new Guid("019d83f5-1626-4deb-b902-adb3178bdd0f"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622129"
                        },
                        new
                        {
                            Id = new Guid("7b833d12-ecdf-4d42-9845-bd61db0974d7"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62213"
                        },
                        new
                        {
                            Id = new Guid("ab87f213-fbf9-4a6e-a0e8-a9159f08738f"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62214"
                        },
                        new
                        {
                            Id = new Guid("ef493529-5de0-4b11-bd6c-04e0a827d244"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62215"
                        },
                        new
                        {
                            Id = new Guid("87511687-047d-4426-9a88-5aa269f1c395"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62216"
                        },
                        new
                        {
                            Id = new Guid("e113ce0a-5f78-4dd4-a2a7-0cdcdcae045e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62217"
                        },
                        new
                        {
                            Id = new Guid("3c351858-f756-4b58-bc62-ae33e2bff185"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62218"
                        },
                        new
                        {
                            Id = new Guid("c0a360dc-7399-455b-ad53-9103c42702b9"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62219"
                        },
                        new
                        {
                            Id = new Guid("53a22cfe-d70d-4fcf-968c-4f341b97bb56"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6222"
                        },
                        new
                        {
                            Id = new Guid("4380b3c8-2ebd-4190-9cbe-5f5917b6dfa9"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6223"
                        },
                        new
                        {
                            Id = new Guid("1fbe6a7e-85c7-41b3-a6e8-6f0181005eb2"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6224"
                        },
                        new
                        {
                            Id = new Guid("e605cac4-fce8-4d4e-910e-67ffc13d719a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6225"
                        },
                        new
                        {
                            Id = new Guid("fd627daa-421a-4ed6-b947-6894887cb8c0"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6226"
                        },
                        new
                        {
                            Id = new Guid("762eadbb-2f8a-42d3-8831-ac83d1a6b16a"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6227"
                        },
                        new
                        {
                            Id = new Guid("3d0cbd21-fa13-4f5f-b74d-3dcb66a05943"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "6228"
                        },
                        new
                        {
                            Id = new Guid("6d0c70e5-9a34-4e42-a10c-12d2c1c85db8"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62290"
                        },
                        new
                        {
                            Id = new Guid("ad96d000-08b2-4924-ac34-49f4d581db4c"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "62291"
                        },
                        new
                        {
                            Id = new Guid("688d9acc-9ba0-4783-bacc-9ddb4173c2b9"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622920"
                        },
                        new
                        {
                            Id = new Guid("dd49c942-b732-45fd-8a6d-2472747c11ca"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622921"
                        },
                        new
                        {
                            Id = new Guid("b7a7f2ed-dc45-4927-a134-abf95b91c9f9"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622922"
                        },
                        new
                        {
                            Id = new Guid("6ff60a32-4520-4174-808f-b89804dce07e"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622923"
                        },
                        new
                        {
                            Id = new Guid("fa74a800-6f01-477f-979a-ee4d9429a513"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622924"
                        },
                        new
                        {
                            Id = new Guid("5d03a975-b5e2-438d-a938-d8356915e565"),
                            Brand = "DISCOVER",
                            Order = 70,
                            Prefix = "622925"
                        },
                        new
                        {
                            Id = new Guid("5e00b7c5-2767-493d-858c-5b66fde72d67"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "627780"
                        },
                        new
                        {
                            Id = new Guid("d2841054-979f-4fd9-9a01-887d4ce0d9eb"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "67410"
                        },
                        new
                        {
                            Id = new Guid("88dad83b-83c3-4069-88c2-b7ee6ddc2a27"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "111111"
                        },
                        new
                        {
                            Id = new Guid("cd9b4256-bb0b-4c62-8b96-1adb296b0993"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "506874"
                        },
                        new
                        {
                            Id = new Guid("539b0701-d51f-4424-9e66-b276bb662586"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "640485"
                        },
                        new
                        {
                            Id = new Guid("86f4e81b-4022-49f0-8b4f-959232eba8ec"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509093"
                        },
                        new
                        {
                            Id = new Guid("8958053f-d01a-4f82-bc3d-e02b7eaed729"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650042"
                        },
                        new
                        {
                            Id = new Guid("d025fc43-c20e-4982-a46a-d6ab64240ebd"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("521c76cd-dd9c-4705-b1fa-850da80fac2f"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509410"
                        },
                        new
                        {
                            Id = new Guid("1996a12f-1f5e-4d52-8d3a-10c4a89f8630"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509005"
                        },
                        new
                        {
                            Id = new Guid("b83a298c-82d3-4956-814b-dae7384a7488"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "650920"
                        },
                        new
                        {
                            Id = new Guid("3d6ce16e-4aed-498c-b231-85acb1750733"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "699988"
                        },
                        new
                        {
                            Id = new Guid("be926869-a7ee-45b9-85d3-9d2a615ce558"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "508757"
                        },
                        new
                        {
                            Id = new Guid("ed5a2d66-2676-4018-a3a5-3c12064145a0"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "680405"
                        },
                        new
                        {
                            Id = new Guid("12882009-01a3-4aae-8a57-4b29a7649cf5"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509423"
                        },
                        new
                        {
                            Id = new Guid("98ab92ae-7016-46cf-a066-b086adde815a"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6538"
                        },
                        new
                        {
                            Id = new Guid("a235020a-9827-4c93-9c5f-e1335658bc8d"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509156"
                        },
                        new
                        {
                            Id = new Guid("847d863a-69aa-4f13-8ee4-0f55714cd315"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509284"
                        },
                        new
                        {
                            Id = new Guid("7d5b1844-e69e-4aff-b9ee-b28ac6fc2414"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "502577"
                        },
                        new
                        {
                            Id = new Guid("ea094b8e-5cb4-4488-b71d-7f1f199bf893"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509004"
                        },
                        new
                        {
                            Id = new Guid("3a49a94a-79de-45b1-97fd-7fa826f17b64"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509294"
                        },
                        new
                        {
                            Id = new Guid("27913d95-9d7c-4934-a27c-da77f468fa00"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509730"
                        },
                        new
                        {
                            Id = new Guid("28d805d5-0ba3-4bc1-9399-c55819b43552"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "509010"
                        },
                        new
                        {
                            Id = new Guid("736a228d-d1be-4bb1-9f98-34e81837737a"),
                            Brand = "ELO",
                            Order = 0,
                            Prefix = "6509"
                        },
                        new
                        {
                            Id = new Guid("08726280-f1b6-40f0-b720-2c337671e48c"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "6507"
                        },
                        new
                        {
                            Id = new Guid("5f06ede1-292a-4c9b-8719-9890880bdcc9"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "650914"
                        },
                        new
                        {
                            Id = new Guid("74ca13cb-8f1f-4a5e-a7ce-828a05c389d0"),
                            Brand = "ELO",
                            Order = 1,
                            Prefix = "509274"
                        },
                        new
                        {
                            Id = new Guid("95b0b90f-0fb7-4d30-831f-5836f275adf2"),
                            Brand = "ELO",
                            Order = 4,
                            Prefix = "506741"
                        },
                        new
                        {
                            Id = new Guid("be79c275-0c2e-4817-a35d-ebafc23a15ac"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6505"
                        },
                        new
                        {
                            Id = new Guid("e3e3eee2-ce55-4bbd-b840-7840b72433f6"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6280"
                        },
                        new
                        {
                            Id = new Guid("bb9cff2d-5de1-47e3-be24-a5f118182119"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6504"
                        },
                        new
                        {
                            Id = new Guid("99edce04-46b4-4046-a8a7-59048557d4c1"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6550"
                        },
                        new
                        {
                            Id = new Guid("d64fe8ba-89ad-45d8-bae5-06f0864bd9b1"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "509023"
                        },
                        new
                        {
                            Id = new Guid("df421d77-42ce-4536-aab0-01b5393806da"),
                            Brand = "ELO",
                            Order = 5,
                            Prefix = "6516"
                        },
                        new
                        {
                            Id = new Guid("746c6af8-763b-4b14-85c4-af6de723fcd0"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650507"
                        },
                        new
                        {
                            Id = new Guid("adf7ca3b-aee0-4b05-8441-0a91274b627c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "636368"
                        },
                        new
                        {
                            Id = new Guid("a07f8613-ef45-427d-9ca1-4231b16b614c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "438935"
                        },
                        new
                        {
                            Id = new Guid("66b0704d-2017-4f93-80a9-7842ac76a570"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "504175"
                        },
                        new
                        {
                            Id = new Guid("8335fbd9-9f8b-47ae-8b02-0e02b4e13da0"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "451416"
                        },
                        new
                        {
                            Id = new Guid("2f88a8c7-25a8-49a7-a994-ad1b6020dacf"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("cacdf39b-765f-4795-be3a-fcb7214d9cee"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509067"
                        },
                        new
                        {
                            Id = new Guid("df792cb3-1851-4a6d-8d40-53380bc4c093"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509049"
                        },
                        new
                        {
                            Id = new Guid("b0275d62-1505-4b36-ae3b-d6fe317ae0b9"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509069"
                        },
                        new
                        {
                            Id = new Guid("dfb83d25-918d-4269-8ba2-aa5c8f782ac3"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509050"
                        },
                        new
                        {
                            Id = new Guid("05e514b9-0ecd-4608-a3da-5226ef0a1f3a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509074"
                        },
                        new
                        {
                            Id = new Guid("5b1428e7-d4ae-4afb-9178-6b5dd54f2c89"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50906"
                        },
                        new
                        {
                            Id = new Guid("9662223b-bd9f-481e-a293-06350d404c55"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("0efffe4e-19d3-4ba9-8d02-a99782a2117a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509045"
                        },
                        new
                        {
                            Id = new Guid("2bc7ea58-9b8a-4596-b0b7-d9d82a090525"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509051"
                        },
                        new
                        {
                            Id = new Guid("9aaab5d3-64b0-4379-98e9-5be970739959"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509046"
                        },
                        new
                        {
                            Id = new Guid("677097eb-3dca-49aa-a861-349737aea62a"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509066"
                        },
                        new
                        {
                            Id = new Guid("32b2666c-3a65-469d-8ab6-3c5fadbdb23c"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "50904"
                        },
                        new
                        {
                            Id = new Guid("b28bcfab-5dec-4c5b-be1f-aabdf3d397f6"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509042"
                        },
                        new
                        {
                            Id = new Guid("38098e34-530e-4fda-8863-b09a4a4ac4dd"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509052"
                        },
                        new
                        {
                            Id = new Guid("bce3dd28-390b-44f6-a9d7-2963690538d3"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509043"
                        },
                        new
                        {
                            Id = new Guid("c2e4dfc9-5879-4b30-92cf-017b2d5cefa3"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509064"
                        },
                        new
                        {
                            Id = new Guid("0a191ab4-3265-409e-9dd3-9aa77bcdad33"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509040"
                        },
                        new
                        {
                            Id = new Guid("6213c361-2936-4171-9f55-b3b3c8a607c9"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "36297"
                        },
                        new
                        {
                            Id = new Guid("f943faed-c3fc-4b8e-90fa-2b1a584479fc"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "5067"
                        },
                        new
                        {
                            Id = new Guid("2cc7b2ce-7529-40b5-8d1b-2ab208c0205e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4576"
                        },
                        new
                        {
                            Id = new Guid("eb9144ff-fde6-4400-917d-c3bae245ed37"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "4011"
                        },
                        new
                        {
                            Id = new Guid("ba07bae5-de24-4814-8d37-28ecf47bd316"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509000"
                        },
                        new
                        {
                            Id = new Guid("68350d71-df3e-435d-a29d-55066293a9d8"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650905"
                        },
                        new
                        {
                            Id = new Guid("0f122ac3-c9c5-4f9e-8f0c-7a7e498cd0f6"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650494"
                        },
                        new
                        {
                            Id = new Guid("39e90751-8331-4290-a400-7fa9f8bf5438"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650485"
                        },
                        new
                        {
                            Id = new Guid("458d0eb6-a67a-45c9-8a06-225095ba8cd0"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509091"
                        },
                        new
                        {
                            Id = new Guid("b227c17f-ac09-4295-9292-ca23976d84c7"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650491"
                        },
                        new
                        {
                            Id = new Guid("5a872234-d9de-4064-82fb-352a54e85882"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "65090"
                        },
                        new
                        {
                            Id = new Guid("8f4aab9d-c445-4f39-9290-8a471efa7b06"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650487"
                        },
                        new
                        {
                            Id = new Guid("4e7d4dd3-6a4d-42b3-ad40-31466a28c195"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "506726"
                        },
                        new
                        {
                            Id = new Guid("6dfb02ee-192f-48d2-99c8-6a7dbf3332d2"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "409835"
                        },
                        new
                        {
                            Id = new Guid("32a55f83-0266-40d3-b9c5-825ecc616ab1"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("27bfc9a1-9ef3-4530-85fb-efc2583b7d37"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650921"
                        },
                        new
                        {
                            Id = new Guid("c06633be-2f73-4fc2-9765-3812e9cc991e"),
                            Brand = "ELO",
                            Order = 10,
                            Prefix = "650912"
                        },
                        new
                        {
                            Id = new Guid("6670c7c3-06d6-49b3-801b-6efc0d98f19f"),
                            Brand = "HIPERCARD",
                            Order = 0,
                            Prefix = "506282"
                        },
                        new
                        {
                            Id = new Guid("c5986fd7-e850-40c9-9047-79f57106d49a"),
                            Brand = "HIPERCARD",
                            Order = 60,
                            Prefix = "38"
                        },
                        new
                        {
                            Id = new Guid("93391f3e-498e-4754-80a0-7281a5ca09f3"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "606282"
                        },
                        new
                        {
                            Id = new Guid("51a027d5-c707-45e0-b84c-ee4fe8346ccf"),
                            Brand = "HIPERCARD",
                            Order = 80,
                            Prefix = "3841"
                        },
                        new
                        {
                            Id = new Guid("58985d65-33a6-4366-8dd4-253871eb19df"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "2131"
                        },
                        new
                        {
                            Id = new Guid("0e4188da-a747-440b-9a62-0e4a3bac889a"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "1800"
                        },
                        new
                        {
                            Id = new Guid("2ab60906-3bec-404c-8989-cb524787e766"),
                            Brand = "JCB",
                            Order = 90,
                            Prefix = "35"
                        },
                        new
                        {
                            Id = new Guid("65a5579a-1bec-4a59-8985-8b0d82a2885b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "546479"
                        },
                        new
                        {
                            Id = new Guid("418648de-f22c-4e02-a92b-6c74c445a16b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509059"
                        },
                        new
                        {
                            Id = new Guid("16c439f4-9b15-4f59-8f25-d512b9dd6a88"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "589916"
                        },
                        new
                        {
                            Id = new Guid("b90d7e08-ce95-4626-bd15-e1c840b9189c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "585988"
                        },
                        new
                        {
                            Id = new Guid("ac37c8ec-de0e-4aef-b459-74a9bbca0d0e"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("6d929da7-ec2d-4214-b36f-93bac4e8906b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "439133"
                        },
                        new
                        {
                            Id = new Guid("fa35ebc4-ae95-4755-bf8c-5487fe3742ee"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "55909"
                        },
                        new
                        {
                            Id = new Guid("3bc777cf-5c1a-46ac-b1b4-fd53d45b8c91"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "53508"
                        },
                        new
                        {
                            Id = new Guid("170330e9-2313-4c53-b961-eabb06009b25"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "320132"
                        },
                        new
                        {
                            Id = new Guid("e4d939bb-efa9-423c-9436-23c0b045a09c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "126820"
                        },
                        new
                        {
                            Id = new Guid("25435b42-5fc1-41e1-906e-4a20ec2a1e59"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576292"
                        },
                        new
                        {
                            Id = new Guid("92aebe51-c8a7-419c-8348-76d4562a0085"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5453"
                        },
                        new
                        {
                            Id = new Guid("11c02a97-ea68-4d40-8dfc-f98fcde11593"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "5379"
                        },
                        new
                        {
                            Id = new Guid("ea837aed-c58b-4ddb-a85b-74b750b8614a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "537993"
                        },
                        new
                        {
                            Id = new Guid("3d04e024-b004-4e9c-ba56-21ca22e65fc5"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "639350"
                        },
                        new
                        {
                            Id = new Guid("9822027e-cf84-4ae4-a704-e0b530517404"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "830050"
                        },
                        new
                        {
                            Id = new Guid("9b99adf1-7ad3-4216-88eb-5247ad25ea1b"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "517349"
                        },
                        new
                        {
                            Id = new Guid("b55478b9-1828-435d-9098-91e6d1c1b89f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("f024b2de-3ea8-4f42-8916-18b964a7c60c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560033"
                        },
                        new
                        {
                            Id = new Guid("5d7e4867-f73b-476f-bc1a-c06d57c36e88"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505381"
                        },
                        new
                        {
                            Id = new Guid("da10feeb-3dfc-4441-b530-6a96bbab723f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("372c1e1d-6da6-4e6f-ae74-9bd5e98d9eb6"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "595922"
                        },
                        new
                        {
                            Id = new Guid("49cb8a2d-288a-4b05-bc22-6dbe65b7230c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("5dc92acc-204b-48fb-8863-d0d8b0fef710"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "7807"
                        },
                        new
                        {
                            Id = new Guid("d2e38307-5b62-46a6-9be1-1e89d81f501f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "509257"
                        },
                        new
                        {
                            Id = new Guid("62524d2e-2653-4242-8d48-36817a9991fb"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502309"
                        },
                        new
                        {
                            Id = new Guid("bec9013a-a868-4259-a00c-632dd261eaae"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "212743"
                        },
                        new
                        {
                            Id = new Guid("c364772c-e29d-418f-9088-21a04d2a8131"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "505316"
                        },
                        new
                        {
                            Id = new Guid("e71142f4-c940-4cde-8c37-475778526b0a"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "720358"
                        },
                        new
                        {
                            Id = new Guid("980ad963-4f15-433e-9e82-af5edd80aeeb"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "502299"
                        },
                        new
                        {
                            Id = new Guid("cf860308-7466-4c8d-be93-f6e6a79429c3"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "330239"
                        },
                        new
                        {
                            Id = new Guid("33e6c3e1-4fd8-4f2b-8d1b-81d860a0d281"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "640245"
                        },
                        new
                        {
                            Id = new Guid("29e6af86-784f-4d62-9a1f-701edbef8766"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "3006"
                        },
                        new
                        {
                            Id = new Guid("ba15f959-82dd-48b8-b452-741c8a74e3ec"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "615292"
                        },
                        new
                        {
                            Id = new Guid("c27513d6-d57e-43a2-8647-d079fb8fec13"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "574080"
                        },
                        new
                        {
                            Id = new Guid("95ea7338-4c7d-40ef-9734-916fe482b4ca"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "608710"
                        },
                        new
                        {
                            Id = new Guid("bd85ac24-7040-4ce0-b011-9b9302c169d7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "507641"
                        },
                        new
                        {
                            Id = new Guid("fb4d74ed-d7d8-4f65-aea2-7fec10fa9d17"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "316811"
                        },
                        new
                        {
                            Id = new Guid("5f8337ad-4351-4c08-98bb-b965ad228c9c"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "569970"
                        },
                        new
                        {
                            Id = new Guid("5e43e8b2-b3e0-4deb-a55e-75008b5503b7"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960397"
                        },
                        new
                        {
                            Id = new Guid("2d790db4-4f72-45cb-ace0-c089fcd3f186"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "220209"
                        },
                        new
                        {
                            Id = new Guid("0f577894-9c74-489c-9868-aa1ab8053b65"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "637095"
                        },
                        new
                        {
                            Id = new Guid("d9b2ed55-e962-4114-9b75-2c72f76a6fa5"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "576096"
                        },
                        new
                        {
                            Id = new Guid("f4a35792-64d5-4a86-8b68-736d58edc789"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "596497"
                        },
                        new
                        {
                            Id = new Guid("d073f1a4-e16d-4e9b-ae76-f7fbd8f4ca5f"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "570209"
                        },
                        new
                        {
                            Id = new Guid("f00923b3-dd48-43bb-999e-a2fc1e3b36e1"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "44027"
                        },
                        new
                        {
                            Id = new Guid("a79bb1ac-62d8-4ba7-8cba-ed97104357db"),
                            Brand = "MASTER",
                            Order = 0,
                            Prefix = "960379"
                        },
                        new
                        {
                            Id = new Guid("e4956d8a-2a04-4fcd-9d22-57408b61f7cf"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "608783"
                        },
                        new
                        {
                            Id = new Guid("7dcdaf17-5a44-4d0d-b68d-aa46e25d58d9"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "750209"
                        },
                        new
                        {
                            Id = new Guid("43c8f398-4f62-4ab1-bc28-d4c87d9ce2f1"),
                            Brand = "MASTER",
                            Order = 1,
                            Prefix = "515894"
                        },
                        new
                        {
                            Id = new Guid("4e3298c3-b678-4f2c-804f-2ab1cba41c57"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2221"
                        },
                        new
                        {
                            Id = new Guid("86fdf28e-b9b8-48bc-bf73-dc7070d5b430"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2222"
                        },
                        new
                        {
                            Id = new Guid("185eb821-d117-4685-ad22-0d80091df950"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2223"
                        },
                        new
                        {
                            Id = new Guid("37a29ac2-329a-43a2-ba5f-d8f1dd86df7e"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2224"
                        },
                        new
                        {
                            Id = new Guid("e78ba8b1-97a8-48c0-9903-d745fe64fd10"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2225"
                        },
                        new
                        {
                            Id = new Guid("bf120782-1aee-4b8c-aa6a-f6223a546e35"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2226"
                        },
                        new
                        {
                            Id = new Guid("9b25bef6-c2b5-44d6-b2a2-c9b3e754be02"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2227"
                        },
                        new
                        {
                            Id = new Guid("557e910b-e244-47ca-8859-038d9b79fcd1"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2228"
                        },
                        new
                        {
                            Id = new Guid("8e6dfe42-bb55-41f5-a2e1-cb4adabd5bde"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2229"
                        },
                        new
                        {
                            Id = new Guid("361043a9-cfb4-4051-9952-7578139a741e"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "223"
                        },
                        new
                        {
                            Id = new Guid("eccc2b67-0a24-4d3b-bf24-7353255d752c"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "224"
                        },
                        new
                        {
                            Id = new Guid("b1794db5-ffe7-460d-9590-6679ec55785d"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "225"
                        },
                        new
                        {
                            Id = new Guid("e9473e88-1553-4235-bcf8-9c390a7840b9"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "226"
                        },
                        new
                        {
                            Id = new Guid("abe5ce0a-4520-4484-9d45-3eba2d8fab84"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "227"
                        },
                        new
                        {
                            Id = new Guid("af0f800d-0301-4458-90dc-61142c273710"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "228"
                        },
                        new
                        {
                            Id = new Guid("14fd766b-5ed6-48a8-a7a6-285dca27abdc"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "229"
                        },
                        new
                        {
                            Id = new Guid("1d7b2c52-de41-4d0b-b3dc-0501c15e7029"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "23"
                        },
                        new
                        {
                            Id = new Guid("8bc204af-8164-4733-a54b-93cddc840373"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "24"
                        },
                        new
                        {
                            Id = new Guid("5866c9af-2a7e-4eff-9994-035314df0635"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "25"
                        },
                        new
                        {
                            Id = new Guid("3c1cbe69-a722-49ff-96d4-b98591aa069e"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "26"
                        },
                        new
                        {
                            Id = new Guid("047c0f44-b4d7-4b15-b2ac-916b61e71fd7"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "271"
                        },
                        new
                        {
                            Id = new Guid("5649ee67-c70d-4e7a-8993-4cfc53f5beb7"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "2720"
                        },
                        new
                        {
                            Id = new Guid("cb9b52e6-b079-4155-9508-8a7ce918fb0e"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "51"
                        },
                        new
                        {
                            Id = new Guid("d4dbde02-b942-4f83-b437-42b7189696ab"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "52"
                        },
                        new
                        {
                            Id = new Guid("e97c6e32-8477-453b-a893-143781fbd35b"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "53"
                        },
                        new
                        {
                            Id = new Guid("540c9c7b-f865-4e2b-bd01-e40aa4f475ac"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "54"
                        },
                        new
                        {
                            Id = new Guid("a517ed0a-a6c8-4b4f-884e-abb9e64a1589"),
                            Brand = "MASTER",
                            Order = 20,
                            Prefix = "55"
                        },
                        new
                        {
                            Id = new Guid("9364e7a1-9c51-4b95-a927-e4f1d3b50c69"),
                            Brand = "NARANJA E NEVADA",
                            Order = 100,
                            Prefix = "589562"
                        },
                        new
                        {
                            Id = new Guid("da4ee1ae-4a46-4a7e-b101-dba4cc336dc3"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "627892"
                        },
                        new
                        {
                            Id = new Guid("c8f0cab3-95de-4989-bf7a-58aa0d95df66"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "502121"
                        },
                        new
                        {
                            Id = new Guid("0fc1c37c-bb1e-460d-b850-f10809fb596b"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "121772"
                        },
                        new
                        {
                            Id = new Guid("62bb1673-9d47-4801-ade1-b1629e231093"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "40064"
                        },
                        new
                        {
                            Id = new Guid("a24d717b-481d-4e84-b7e3-ba0da06cc8a8"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "444125"
                        },
                        new
                        {
                            Id = new Guid("6bd521c8-8f0d-4b86-b3d9-b57923be374f"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "798431"
                        },
                        new
                        {
                            Id = new Guid("57544e75-332c-4a8a-88ae-2e4373591bbe"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "48546"
                        },
                        new
                        {
                            Id = new Guid("9a94673a-54f3-4f09-93d1-16ef865614c5"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "988442"
                        },
                        new
                        {
                            Id = new Guid("75ef5156-9be7-4b8e-a2fc-d6487ddd04ab"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "566269"
                        },
                        new
                        {
                            Id = new Guid("27e20732-3f4c-4ef5-b1d4-cb3116d75611"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "970800"
                        },
                        new
                        {
                            Id = new Guid("c302dd70-0829-4d81-a1f4-f4dd00c14577"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "560780"
                        },
                        new
                        {
                            Id = new Guid("2d61317d-82c5-4f58-a0e6-8499a4c67950"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "984428"
                        },
                        new
                        {
                            Id = new Guid("7e90319e-b81b-4f36-ad6c-1f9959997b28"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "636355"
                        },
                        new
                        {
                            Id = new Guid("ce53323d-7965-40ff-9bb9-45dcb5afdde7"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "27728"
                        },
                        new
                        {
                            Id = new Guid("b2b8f277-605b-49b5-a12c-9b1bc386df26"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "107915"
                        },
                        new
                        {
                            Id = new Guid("d2170b50-fe3d-40db-b080-d662011e4607"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "210790"
                        },
                        new
                        {
                            Id = new Guid("3bc2f9e9-9a4c-4ae3-bfc9-095f23615327"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "854644"
                        },
                        new
                        {
                            Id = new Guid("0d0241fd-e17c-4fbf-8c01-e2feb1cd2fb6"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "33994"
                        },
                        new
                        {
                            Id = new Guid("5babcabd-b249-4acb-9569-79fdc4a56614"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "985966"
                        },
                        new
                        {
                            Id = new Guid("d252ac93-ec82-4507-86db-895e98cd3d41"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "960421"
                        },
                        new
                        {
                            Id = new Guid("1f2da3f2-4515-44da-8a7d-a10526c6f18d"),
                            Brand = "VISA",
                            Order = 0,
                            Prefix = "186307"
                        },
                        new
                        {
                            Id = new Guid("328a0b13-d4af-48e8-a874-e9899c44c20a"),
                            Brand = "VISA",
                            Order = 5,
                            Prefix = "4984"
                        },
                        new
                        {
                            Id = new Guid("94270a91-e4c1-4bc9-9d7f-5bb94c21c444"),
                            Brand = "VISA",
                            Order = 110,
                            Prefix = "4"
                        });
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BraspagProvider")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("FeevCheckout.Models.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankAgency")
                        .HasColumnType("text");

                    b.Property<string>("BankNumber")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CheckingAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("ExtraData")
                        .HasColumnType("jsonb");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method");

                    b.Property<JsonDocument>("Response")
                        .HasColumnType("jsonb");

                    b.Property<PaymentAttemptStatus>("Status")
                        .HasColumnType("payment_attempt_status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("TransactionId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SuccessfulPaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("SuccessfulPaymentAttemptId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FeevCheckout.Models.Credential", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("FeevCheckout.Models.PaymentAttempt", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Product", b =>
                {
                    b.HasOne("FeevCheckout.Models.Transaction", "Transaction")
                        .WithMany("Products")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.HasOne("FeevCheckout.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeevCheckout.Models.PaymentAttempt", "SuccessfulPaymentAttempt")
                        .WithMany()
                        .HasForeignKey("SuccessfulPaymentAttemptId");

                    b.OwnsOne("FeevCheckout.Models.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Document")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerDocument");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CustomerName");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("FeevCheckout.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("CustomerTransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressCity");

                                    b2.Property<string>("Complement")
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressComplement");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressDistrict");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressNumber");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressState");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressStreet");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CustomerAddressZipCode");

                                    b2.HasKey("CustomerTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerTransactionId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("SuccessfulPaymentAttempt");
                });

            modelBuilder.Entity("FeevCheckout.Models.Transaction", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
